import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import vm from 'node:vm';
const require=createRequire(import.meta.url),T=require('../lib/three.min.js'),S=require('../assets/character-sculpt.js'),F=require('../assets/character-face.js'),H=require('../story/tower-heroes-core.js'),P=require('../story/tower-party-core.js'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
function env(){const e=vm.createContext({THREE:T,CharacterSculpt:S,CharacterFace:F,TowerHeroes:H,TowerPartyCore:P});e.window=e;const start=html.indexOf('function buildCharacter(cd)'),end=html.indexOf('\n}',start)+2;vm.runInContext(html.slice(start,end),e);vm.runInContext(readFileSync(new URL('../story/tower-heroes-visuals.js',import.meta.url),'utf8'),e);return e;}
function budget(model){let triangles=0,meshes=0;model.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;assert.equal(o.material.map,null);}assert.ok(!o.isLight);});return {triangles,meshes};}
test('seven male/female job silhouettes have sculpted heads, torsos and limbs without heavy textures',()=>{
  const e=env(),shapes=new Set();for(const job of Object.keys(H.JOBS).filter(job=>job!=='robot'))for(const sex of ['male','female']){const model=e.TowerHeroVisuals.base(job,e.buildCharacter,'hero',sex);assert.equal(model.userData.headMesh.geometry.type,'SphereGeometry');assert.equal(model.userData.body.geometry.type,'LatheGeometry');assert.equal(model.userData.armR.geometry.type,'LatheGeometry');assert.equal(model.userData.legR.geometry.type,'LatheGeometry');assert.equal(model.userData.heroSex,sex);shapes.add(model.userData.heroShape);assert.ok(budget(model).triangles<7000);assert.ok(budget(model).meshes<65);model.updateMatrixWorld(true);const b=new T.Box3().setFromObject(model);assert.ok(b.max.y<3&&b.min.y>-.1);}
  assert.equal(shapes.size,7);assert.ok(html.indexOf('character-sculpt.js')<html.indexOf('function buildCharacter'));
});
test('expressions include rounded eyes, warning, hurt, casting, talking and joy; update reuses all geometry',()=>{
  const e=env(),model=e.TowerHeroVisuals.base('healer',e.buildCharacter,'hero','female'),face=model.userData.face,before=budget(model),signatures=new Set();let t=.4;for(const mood of F.moods){F.update(model,t,mood);t+=.25;signatures.add(JSON.stringify([face.eyes[0].scale.y,face.brows[0].rotation.z,face.mouth.scale.toArray(),face.teeth.visible]));}assert.ok(signatures.size>=7);assert.ok(face.whites.length===2&&face.cheeks.length===2);assert.equal(F.react(model,'invalid'),false);assert.ok(F.react(model,'happy',1));F.update(model,t,'calm');assert.equal(face.mood,'happy');F.update(model,t+.1,'hurt');assert.equal(face.mood,'hurt');for(let i=0;i<200;i++)F.update(model,t+.2+i*.02,'calm');assert.equal(face.mood,'calm');assert.deepEqual(budget(model),before);
});
test('all three armor families have shaped body volume and rounded helmets, retaining mount and tier rules',()=>{
  const e=env();for(const kind of ['heavy_armor','light_armor','robe']){const gear=e.TowerHeroVisuals.gear(T,kind);assert.ok(gear.children.some(o=>o.geometry?.type==='LatheGeometry'));assert.ok(budget(gear).triangles<4000);}for(const kind of ['heavy_helm','light_hood']){const gear=e.TowerHeroVisuals.gear(T,kind);assert.ok(gear.children.some(o=>o.geometry?.type==='SphereGeometry'));assert.equal(gear.userData.baseKind,kind);}
});
function fingerprint(model){const parts=[];model.traverse(o=>{if(o.isMesh)parts.push([o.name,o.geometry.type,Array.from(o.geometry.attributes.position.array),o.material.color.getHex(),o.position.toArray(),o.scale.toArray()]);});return createHash('sha256').update(JSON.stringify(parts)).digest('hex');}
test('fourteen adult variants have different facial sculpture, eyebrows, hair and palettes, including with helmets',()=>{
  const e=env(),faces=new Set(),looks=new Set();for(const job of Object.keys(H.JOBS).filter(job=>job!=='robot')){
    const models=['male','female'].map(sex=>e.TowerHeroVisuals.base(job,e.buildCharacter,'traveller',sex));
    for(const model of models){const head=model.userData.head;faces.add(JSON.stringify(Array.from(model.userData.headMesh.geometry.attributes.position.array)));looks.add(fingerprint(head));assert.equal(model.userData.adultDesign,true);assert.equal(model.userData.face.lids.length,2);assert.equal(model.userData.face.lips.length,2);assert.ok(head.children.find(c=>c.name==='nose-bridge'));assert.equal(head.children.filter(c=>c.name==='nostril').length,2);}
    assert.notDeepEqual(models[0].scale.toArray(),models[1].scale.toArray(),job);assert.notEqual(e.TowerHeroVisuals.style(job,'male').hair,e.TowerHeroVisuals.style(job,'female').hair,job);
    const helmet=H.JOBS[job].armor==='heavy'?'heavy_helm':H.JOBS[job].armor==='robe'?'rune_crown':'light_hood';
    for(const model of models){e.TowerHeroVisuals.dress(T,model,{helmet:{kind:helmet,slot:'helmet',durability:9},armor:null,weapon:null,shield:null},()=>{});assert.equal(model.userData.heroPieces[0].userData.wearVariant,model.userData.heroSex);const hair=model.userData.head.children.find(c=>c.name==='profession-hair');assert.ok(hair);assert.equal(hair.visible,!model.userData.knightSculpt,'only the male knight short cut fits fully under his helmet');}
  }assert.ok(faces.size>=10);assert.equal(looks.size,14);
});
test('all three tiers of clothing adapt male/female geometry without mutating equipment or adding equip locks',()=>{
  const e=env();for(const [base,job]of [['heavy_armor','swordsman'],['light_armor','scout'],['robe','mage'],['heavy_helm','smith'],['light_hood','chef'],['rune_crown','healer']])for(const tier of [1,2,3]){
    const kind=H.tierKind(base,tier),male=e.TowerHeroVisuals.gear(T,kind,{job,sex:'male'}),female=e.TowerHeroVisuals.gear(T,kind,{job,sex:'female'});assert.equal(male.userData.tier,tier);assert.equal(female.userData.baseKind,base);assert.notEqual(fingerprint(male),fingerprint(female),kind);assert.ok(budget(female).triangles<5000);
  }
  const item={id:'same-item',kind:'heavy_armor',slot:'armor',durability:12,maxDurability:15},before=JSON.stringify(item),model=e.TowerHeroVisuals.base('swordsman',e.buildCharacter,'hero','male'),equipment={helmet:null,armor:item,weapon:null,shield:null};let disposed=0;e.TowerHeroVisuals.dress(T,model,equipment,()=>disposed++);const old=model.userData.heroPieces[0];model.userData.heroSex='female';e.TowerHeroVisuals.dress(T,model,equipment,()=>disposed++);assert.equal(disposed,1);assert.equal(old.parent,null);assert.equal(model.userData.heroPieces.length,1);assert.equal(model.userData.heroPieces[0].userData.wearVariant,'female');assert.equal(JSON.stringify(item),before);
});
test('female smith has a soft adult face and two braids; female archer is shorter and less slender',()=>{
  const e=env(),smith=e.TowerHeroVisuals.base('smith',e.buildCharacter,'hero','female'),archer=e.TowerHeroVisuals.base('archer',e.buildCharacter,'hero','female'),male=e.TowerHeroVisuals.base('archer',e.buildCharacter,'hero','male');
  const braids=[];smith.traverse(o=>{if(o.userData.braidSide){assert.equal(o.geometry.type,'TubeGeometry');braids.push(o.userData.braidSide);}});assert.deepEqual(braids.sort(),[-1,1]);assert.equal(smith.userData.adultDesign,true);assert.match(e.TowerHeroVisuals.portrait('smith','female'),/twin-braids/);assert.ok(archer.scale.y<male.scale.y);assert.ok(archer.scale.x>male.scale.x);assert.equal(smith.userData.headMesh.geometry.type,'SphereGeometry');
  const helmet={kind:'heavy_helm',slot:'helmet',durability:30},equipment={helmet,armor:null,shield:null,weapon:null};e.TowerHeroVisuals.dress(T,smith,equipment,()=>{}, {showHelmet:false});assert.equal(smith.userData.heroPieces.length,0);assert.ok(smith.userData.head.children.find(o=>o.name==='hair-crown').visible);e.TowerHeroVisuals.dress(T,smith,equipment,()=>{}, {showHelmet:true});assert.equal(smith.userData.heroPieces.length,1);assert.equal(helmet.durability,30);
});
