import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),H=require('../story/tower-heroes-core.js'),P=require('../story/tower-party-core.js'),X=require('../story/tower-expedition-core.js'),E=require('../story/tower-encounters.js'),R=H.ROBOT;
const fresh=(job='smith',seed=123)=>H.enable(P.enable(C.newRun({seed}),job).run).run;
function oldGear(kind,roll,left=1,version=5){const g=C.createGear(kind,99,123,'v6-migration'),base=C.originalDurabilityMultiplier(kind);let maximum;if(version===5)maximum=Math.round(roll*base/2)*2;else if(version===4)maximum=Math.round(roll*base/2);else if(version===3)maximum=Math.round(roll*base*.75);else if(version===2)maximum=Math.round(roll*base*.15);else maximum=roll;return {...g,bonus:0,name:C.GEAR[kind].name,defense:C.GEAR[kind].slot==='weapon'?0:C.GEAR[kind].defense,maxDurability:maximum,durability:Math.floor(maximum*left),...(version?{durabilityVersion:version}:{durabilityVersion:undefined})};}
test('v6 gives book/pan an exact 25% increase and each tier a higher minimum roll',()=>{
  assert.equal(C.DURABILITY_VERSION,6);
  for(const base of ['spellbook','cooking_pan'])for(let tier=1;tier<=5;tier++)for(let roll=C.durabilityMinimumRoll(H.tierKind(base,tier));roll<=20;roll++)assert.equal(C.durabilityForRoll(H.tierKind(base,tier),roll),Math.round(roll*20*1.25));
  for(const base of H.BASE_GEAR.map(g=>g.kind))for(let tier=1;tier<=5;tier++)for(let seed=1;seed<=100;seed++){const kind=H.tierKind(base,tier),g=C.createGear(kind,99,seed,'v6-new');assert.equal(C.durabilityMinimumRoll(kind),tier+2);assert.ok(g.maxDurability>=C.durabilityForRoll(kind,tier+2));assert.ok(g.maxDurability<=C.durabilityForRoll(kind,10));assert.deepEqual(C.validateGear(g),g);}
});
test('v1 through v5 ordinary gear migrate proportionally once, including old low high-tier rolls and zeros',()=>{
  for(const base of ['longsword','spellbook','cooking_pan','robe','buckler'])for(let tier=1;tier<=5;tier++)for(const version of [undefined,2,3,4,5])for(const roll of [3,5,10])for(const left of [0,.1,.37,1]){const kind=H.tierKind(base,tier),old=oldGear(kind,roll,left,version),raw=structuredClone(old),g=C.validateGear(old);assert.ok(g,kind+'/'+version+'/'+roll);assert.deepEqual(old,raw);assert.equal(g.maxDurability,C.durabilityForRoll(kind,roll));assert.equal(g.durability,old.durability===0?0:Math.max(1,Math.round(old.durability*g.maxDurability/old.maxDurability)));assert.equal(g.id,old.id);assert.equal(g.defense,old.defense);assert.deepEqual(C.validateGear(JSON.parse(JSON.stringify(g))),g);}
});
test('v6 rejects invalid source maxima and malformed new forge accumulators',()=>{
  const g=C.createGear('spellbook',99,1,'validation');for(const bad of [{...g,durabilityVersion:7},{...g,maxDurability:g.maxDurability+1},{...g,forge:{trait:'durable',level:1,reserve:0,wearCredit:10}},{...g,forge:{trait:'durable',level:1,reserve:0,wearCredit:-1}},{...g,forge:{trait:'light',level:1,reserve:0,wearCredit:1}}])assert.equal(C.validateGear(bad),null);
});
test('ordinary gear preserves validated affixes through migration and robot parts never gain them',()=>{
  const old=oldGear('spellbook',3,.37);old.affix={id:'burn',power:1};old.affixRoll=2;const migrated=C.validateGear(old);assert.ok(migrated);assert.deepEqual(migrated.affix,old.affix);assert.equal(migrated.affixRoll,2);assert.deepEqual(C.validateGear(migrated),migrated);assert.equal(C.validateGear({...old,affix:{id:'unknown',power:1}}),null);assert.equal(C.validateGear({...old,affixRoll:-1}),null);for(const kind of ['robot_fists','robot_shell','robot_core'])assert.equal(C.validateGear({...C.createGear(kind,99,123,'affix-forbidden'),affix:{id:'burn',power:1},affixRoll:1}),null);
});
test('durable forge saves exactly 10% or 20% deterministically across save/reload and repairs',()=>{
  for(const level of [1,2]){const run=fresh();let g=C.createGear('longsword',99,1,'durable');g.durability=g.maxDurability=200;g.forge={trait:'durable',level,reserve:0};let spent=0;for(let i=0;i<30;i++){const before=g.durability;X.wear(run,g);spent+=before-g.durability;if(i===6)g=C.validateGear(JSON.parse(JSON.stringify(g)));assert.ok(g);if(i===18)g.durability=g.maxDurability;}assert.equal(spent,30*(1-level*.1));assert.equal(g.forge.wearCredit,0);}
});
test('legacy reserve is preserved and consumed before sustainable credit; other protection does not grow credit',()=>{
  const run=fresh();let g=C.createGear('longsword',99,1,'reserve');g.forge={trait:'durable',level:2,reserve:3};g=C.validateGear(g);assert.deepEqual(g.forge,{trait:'durable',level:2,reserve:3,wearCredit:0});const before=g.durability;for(let i=0;i<3;i++)X.wear(run,g);assert.equal(g.durability,before);assert.equal(g.forge.reserve,0);assert.equal(g.forge.wearCredit,0);run.equipment.weapon=g;H.setBuff(run,'hero','fortify',30,2);H.wear(run,'hero',g);H.wear(run,'hero',g);assert.equal(g.durability,before);assert.equal(g.forge.wearCredit,0);for(let i=0;i<5;i++)X.wear(run,g);assert.equal(g.durability,before-4);assert.equal(g.forge.wearCredit,0);g.durability=0;X.wear(run,g);assert.equal(g.durability,0);
});
test('new forging starts no consumable reserve and upgrading does not reset saved credit',()=>{
  let run=fresh();run.coins=999;run.party.journey.scrap=99;run.party.journey.materials.ironore=9;const id=run.equipment.weapon.id;let out=X.forge(run,id,'durable');assert.ok(out.ok);run=out.run;assert.deepEqual(run.equipment.weapon.forge,{trait:'durable',level:1,reserve:0,wearCredit:0,smith:true},'camp forging by the party smith leaves the smith mark');X.wear(run,run.equipment.weapon);out=X.forge(run,id,'durable');assert.ok(out.ok);assert.equal(out.run.equipment.weapon.forge.wearCredit,2,'durable level one plus the smith mark credit two per wear');assert.equal(out.run.equipment.weapon.forge.reserve,0);
});
test('percentage emergency repair is capped, cannot restore cores or broken gear, and cannot exceed full',()=>{
  const gear=C.createGear('longsword',99,1,'emergency');gear.maxDurability=200;gear.durability=100;assert.equal(X.emergencyRepairAmount(gear,8),16);assert.equal(X.emergencyRepairAmount(gear,18),30);gear.durability=198;assert.equal(X.emergencyRepairAmount(gear,18),2);gear.durability=0;assert.equal(X.emergencyRepairAmount(gear,18),0);assert.equal(X.emergencyRepairAmount(C.createGear('robot_core',99,1,'core'),18),0);
});
function repairFixture(){const run=fresh('swordsman',1);run.coins=999;run.party.journey.scrap=99;const shop=E.merchantOffers(run.floor,run.seed,true)[0],service=E.serviceContext(run,shop.id);for(const g of H.allGear(run))g.durability=g.maxDurability;const matching=H.allGear(run).filter(g=>E.merchantHandles(service.merchantId,g));assert.ok(matching.length>=2);return {run,service,matching};}
test('repair-all optional below threshold is strict and default still sums unchanged full repair quotes',()=>{
  const {run,service,matching}=repairFixture();matching[0].durability=Math.floor(matching[0].maxDurability*.69);matching[1].durability=Math.ceil(matching[1].maxDurability*.7);const all=X.repairAllQuote(run,service),low=X.repairAllQuote(run,service,{below:.7});assert.equal(all.entries.length,2);assert.deepEqual(low.entries.map(g=>g.id),[matching[0].id]);assert.equal(all.coins,all.entries.reduce((n,g)=>n+X.repairQuote(run,g.id,service).coins,0));const out=X.repairAll(run,run.revision,service,{below:.7});assert.ok(out.ok);assert.equal(H.allGear(out.run).find(g=>g.id===matching[0].id).durability,matching[0].maxDurability);assert.equal(H.allGear(out.run).find(g=>g.id===matching[1].id).durability,matching[1].durability);assert.equal(X.repairAllQuote(run,service,{below:2}).allowed,false);
});
test('explicit minor-loss pooled maintenance is cheaper, atomic, excludes broken and foreign gear, preserves credit',()=>{
  const {run,service,matching}=repairFixture();for(const g of matching){g.durability--;g.forge={trait:'durable',level:1,reserve:0,wearCredit:7};}const all=X.repairAllQuote(run,service),q=X.maintenanceAllQuote(run,service);assert.ok(q.allowed&&q.affordable);assert.ok(q.coins<all.coins);assert.ok(q.parts<all.parts);const before=structuredClone(run),out=X.maintenanceAll(run,run.revision,service);assert.ok(out.ok);assert.deepEqual(run,before);for(const entry of q.entries){const g=H.allGear(out.run).find(g=>g.id===entry.id);assert.equal(g.durability,g.maxDurability);assert.equal(g.forge.wearCredit,7);}assert.equal(out.run.coins,run.coins-q.coins);assert.equal(out.run.party.journey.scrap,run.party.journey.scrap-q.parts);run.coins=0;assert.equal(X.maintenanceAll(run,run.revision,service).ok,false);assert.equal(X.maintenanceAll(before,before.revision+1,service).ok,false);assert.equal(X.maintenanceAllQuote(before,{...service,floor:98}).allowed,false);
});
test('fixed robot parts/cores migrate v5 to v6 without altering durability or giving extra cores',()=>{
  const run=fresh('robot');for(const g of H.allGear(run))g.durabilityVersion=5;const old=structuredClone(run),saved=C.validateSave(run);assert.ok(saved);for(const g of H.allGear(saved)){const previous=H.allGear(old).find(x=>x.id===g.id);assert.equal(g.durabilityVersion,6);assert.equal(g.durability,previous.durability);assert.equal(g.maxDurability,previous.maxDurability);}assert.equal(saved.equipment.core2,null);assert.deepEqual(C.validateSave(saved),saved);
});
test('a small wound uses the lower-tier core first regardless of slot, and depleted cores still vanish',()=>{
  const run=fresh('robot');H.state(run).level=10;run.equipment.core1=C.createGear('robot_core_t5',99,1,'high');run.equipment.core2=C.createGear('robot_core',99,1,'low');H.setHp(run,'hero',H.maxHp(run,'hero')-1);assert.deepEqual(R.coreRepairOrder(run.equipment),['core2','core1']);R.tick(run,'hero',3);assert.equal(run.equipment.core2.durability,99);assert.equal(run.equipment.core1.durability,300);run.equipment.core2.durability=1;H.setHp(run,'hero',H.maxHp(run,'hero')-1);R.tick(run,'hero',3);assert.equal(run.equipment.core2,null);assert.equal(run.equipment.core1.durability,300);assert.equal(X.repairQuote(run,run.equipment.core1.id),null);
});
test('upgraded shells expose distinct capped control resistance without changing armor mitigation',()=>{
  const run=fresh('robot');for(let tier=1;tier<=5;tier++){run.equipment.armor=C.createGear(R.kind('robot_shell',tier),99,1,'resistance');assert.ok(Math.abs(R.controlResistance(run,'hero')-(tier-1)*.05)<1e-8);}run.equipment.armor.durability=0;assert.equal(R.controlResistance(run,'hero'),0);
});
