import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),T=require('../lib/three.min.js'),H=require('../story/tower-heroes-core.js'),M=require('../story/tower-combat-motion.js'),CM=require('../assets/character-motion.js');
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),start=html.indexOf('function buildCharacter('),builder=html.slice(start,html.indexOf('\n}',start)+2),visualSource=readFileSync(new URL('../story/tower-heroes-visuals.js',import.meta.url),'utf8');
function fixture(sex='male',tier=1,modern=true){const e=vm.createContext({THREE:T,TowerHeroes:H,CharacterSculpt:require('../assets/character-sculpt.js'),CharacterFace:require('../assets/character-face.js'),CharacterMotion:CM,...(modern?{TowerCombatMotion:M}:{})});e.window=e;vm.runInContext(builder,e);vm.runInContext(visualSource,e);const V=e.TowerHeroVisuals,m=V.base('healer',e.buildCharacter,'hero',sex),equipment={weapon:{kind:H.tierKind('spellbook',tier),slot:'weapon',durability:100},armor:{kind:H.tierKind('robe',tier),slot:'armor',durability:100}};V.dress(T,m,equipment,()=>{});return {V,m,book:m.userData.heroPieces.find(p=>p.userData.baseKind==='spellbook'),equipment};}
const refs=m=>{const out=[];m.traverse(p=>out.push([p,p.geometry,p.material]));return out;};
function frame(f,action,progress,variant=0,family=''){M.begin(f.m,action,1,family?{presentation:{motion:family}}:undefined);Object.assign(M.state(f.m),{elapsed:progress,variant});f.V.pose(f.m,0,1,false,0);f.m.updateMatrixWorld(true);}
const close=(a,b,label)=>assert.ok(Math.abs(a-b)<1e-7,label+': '+a+' != '+b);
test('all ten healer book variants rest closed in only the right hand, including the first dressed frame',()=>{
  for(const sex of ['male','female'])for(let tier=1;tier<=5;tier++){const f=fixture(sex,tier),{m,book}=f;assert.equal(book.parent,m.userData.armR);assert.equal(book.userData.bookOpen,0);assert.deepEqual(book.position.toArray(),[0,-.36,.13]);const leaves=book.children.filter(p=>p.userData.bookSide);assert.equal(leaves.length,2);for(const p of leaves){close(p.rotation.z,p.userData.bookSide*Math.PI/2,'closed cover hinge');close(p.position.x,p.userData.bookSide*.082,'separated page blocks');}close(m.userData.armL.rotation.x,0,'free left hand');close(m.userData.armL.rotation.z,.05,'free left hand');const closed=new T.Box3().setFromObject(book).getSize(new T.Vector3());f.V.bookPose(book,1);const open=new T.Box3().setFromObject(book).getSize(new T.Vector3());assert.ok(open.x>closed.x*2,'the actual cover geometry opens, not a replaced icon');assert.ok(book.userData.authoredParts.includes('book-bound-cover'));assert.ok(book.userData.authoredParts.includes('book-bound-pages'));}
});
test('both attacks and support casts open the real covers smoothly, keep the hand grip, then close or cancel safely',()=>{
  for(const sex of ['male','female'])for(let tier=1;tier<=5;tier++){const f=fixture(sex,tier),resources=refs(f.m),input=JSON.stringify(f.equipment);for(const [action,variant,family]of [['attack',0,''],['attack',1,''],['skill',0,'cast'],['skill',0,'heal'],['skill',0,'ward'],['skill',0,'cleanse']])for(const p of [0,.08,.22,.48,.7,.94,1]){frame(f,action,p,variant,family);close(f.book.userData.bookOpen,p===1?0:Math.min(1,p/.22,(1-p)/.18),'cover interpolation');const hand=f.m.userData.armR.localToWorld(new T.Vector3(0,-.36,.13)),grip=f.book.localToWorld(new T.Vector3(...f.book.userData.contact.grip));assert.ok(hand.distanceTo(grip)<1e-7,'the articulated book never floats off its right palm');if(p===.48){const axis=new T.Vector3(...f.book.userData.contact.axis).transformDirection(f.book.matrixWorld);assert.ok(axis.z>.9,'magic still projects forward');}}
    frame(f,'charge',.9,0,'cast');assert.equal(f.book.userData.bookOpen,1);M.cancel(f.m);f.V.pose(f.m,0,1,false,0);assert.equal(f.book.userData.bookOpen,0);assert.deepEqual(refs(f.m),resources,'casting does not recreate covers, geometry or materials');assert.equal(JSON.stringify(f.equipment),input,'no equipment or durability changes');}
});
test('walking keeps a closed one-handed book and reuses geometry, materials and articulation',()=>{
  for(const sex of ['male','female']){const f=fixture(sex,5);CM.update(f.m,0,0,false);f.V.pose(f.m,0,1,false,0);const before=refs(f.m);for(let i=0;i<160;i++){CM.update(f.m,1/30,i/30,true);f.V.pose(f.m,0,1,false,1/30);assert.equal(f.book.userData.bookOpen,0);assert.equal(f.book.parent,f.m.userData.armR);}assert.deepEqual(refs(f.m),before);}
});
test('legacy motion fallback also rests closed and opens only during an attack',()=>{
  for(const sex of ['male','female']){const f=fixture(sex,1,false);assert.equal(f.book.userData.bookOpen,0);f.V.pose(f.m,.5,1,false,0);assert.equal(f.book.userData.bookOpen,1);f.V.pose(f.m,0,1,false,0);assert.equal(f.book.userData.bookOpen,0);assert.equal(f.book.parent,f.m.userData.armR);close(f.m.userData.armL.rotation.x,0,'free left hand');}
});
