import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const require=createRequire(import.meta.url),C=require('../assets/maze-sight-core.js'),T=require('../lib/three.min.js'),Story=require('../story/story-core.js');
const maze=(w=5,h=5)=>({s:C.create(w,h),hw:Array.from({length:h-1},()=>Array(w).fill(false)),vw:Array.from({length:h},()=>Array(w-1).fill(false))});
test('shopping full vision bypasses fog, wall sight filtering and minimap masks in every view',()=>{const ctx=vm.createContext({MazeSightCore:C,performance:{now:()=>1000}});vm.runInContext(readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),ctx);const api=ctx.MazeSight,{hw,vw}=maze(3,3);vw.forEach(row=>row[0]=true);const g={mazeW:3,mazeH:3,cell:4,wallH:3,wallT:.3,wallBoxes:[],hWalls:hw,vWalls:vw,view:'tp',px:-4,pz:0},scene=new T.Scene(),wall=new T.InstancedMesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial(),2),actor=new T.Group();scene.add(wall,actor);scene.updateMatrixWorld(true);const f={T,g,scene,wall,radius:1,force:true,objects:()=>[actor]};api.update(f);assert.equal(api.visible(0,0),false);for(const view of ['tp','top','fp']){g.view=view;api.render({...f,fullVision:true},{render(){assert.equal(actor.visible,true);assert.equal(wall.visible,true);assert.equal(scene.getObjectByName('maze-sight-layer'),undefined);}},null);assert.equal(api.active(),false);assert.equal(api.visible(999,999),true);assert.equal(api.cellVisible(2,2),true);api.map({fillRect(){throw Error('shop map must not be masked');}},0,1,1);assert.equal(api.stats(),null);}g.view='tp';api.update(f);assert.equal(api.active(),true);assert.equal(api.visible(0,0),false);api.reset();const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/f\.fullVision=isShop\(\)/);assert.match(html,/scene\.fog=theme\.id==='shop'\?null:/);});
test('history is a low floor plan, fog does not become grey and removed walls stay removed',()=>{const ctx=vm.createContext({MazeSightCore:C,performance:{now:()=>1000},MagicMap:{isRevealed:()=>true}});vm.runInContext(readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),ctx);const {hw,vw}=maze(3,3);vw.forEach(row=>row[0]=true);const scene=new T.Scene(),wall=new T.InstancedMesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial(),1),g={mazeW:3,mazeH:3,cell:4,wallH:3,wallT:.3,wallBoxes:[{boundary:false,type:'v',gx:0,gy:1,minX:-2.15,maxX:-1.85,minZ:-2,maxZ:2}],hWalls:hw,vWalls:vw,view:'tp',px:-4,pz:0};scene.add(wall);const f={T,g,scene,wall,radius:8,force:true,objects:()=>[]};ctx.MazeSight.update(f);const [live,memory,fog,shade]=scene.getObjectByName('maze-sight-layer').children;assert.equal(live.count,1);assert.equal(memory.geometry.parameters.height,.08);assert.equal(fog.material.fog,false);assert.equal(shade.material.fog,false);vw[1][0]=false;ctx.MazeSight.update(f);assert.equal(live.count,0);ctx.MazeSight.reset();});
test('a wall blocks current sight even after terrain is revealed',()=>{const {s,hw,vw}=maze();vw.forEach(row=>row[1]=true);C.update(s,.5,2.5,hw,vw,8);assert.equal(s.current[2*5+2],0);C.reveal(s,hw,vw);assert.equal(s.seen[12],1);assert.equal(s.current[12],0);assert.equal(C.line(s,.5,2.5,2.5,2.5,hw,vw),false);});
test('diagonal corners cannot leak through touching walls; symmetry holds',()=>{const {s,hw,vw}=maze(2,2);hw[0][0]=true;assert.equal(C.line(s,.5,.5,1.5,1.5,hw,vw),false);assert.equal(C.line(s,1.5,1.5,.5,.5,hw,vw),false);hw[0][0]=false;assert.equal(C.line(s,.5,.5,1.5,1.5,hw,vw),true);});
test('out of sight topology remains historical until actually revisited',()=>{const {s,hw,vw}=maze();hw[3][3]=true;C.update(s,3.5,3.5,hw,vw,1);assert.equal(s.horizontal[18],1);C.update(s,.5,.5,hw,vw,1);hw[3][3]=false;C.update(s,.5,.5,hw,vw,1);assert.equal(s.horizontal[18],1);C.update(s,3.5,3.5,hw,vw,1);assert.equal(s.horizontal[18],0);});
test('sight snapshots are bounded and preserve old saves',()=>{const {s,hw,vw}=maze();C.update(s,.5,.5,hw,vw);const save=C.snapshot(s);assert.deepEqual(C.snapshot(C.restore(save)),save);assert.equal(C.restore({...save,horizontal:[99]}),null);assert.equal(C.restore({...save,w:999}),null);const run=Story.newRun({seed:3});assert.ok(Story.validateSave(run));run.engine.sightMemory={...save,key:'abc'};assert.ok(Story.validateSave(run).engine.sightMemory);const next=Story.descend(run);assert.ok(next.ok);assert.equal(next.run.engine.sightMemory,undefined);});
test('render hides full actors and effects, restores gameplay state, and owns bounded resources',()=>{const ctx=vm.createContext({MazeSightCore:C,performance:{now:()=>1000}});vm.runInContext(readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),ctx);const api=ctx.MazeSight,{hw,vw}=maze(3,3);vw.forEach(row=>row[0]=true);const g={mazeW:3,mazeH:3,cell:4,wallH:3,wallT:.3,wallBoxes:[],hWalls:hw,vWalls:vw,view:'tp',px:-4,pz:0},scene=new T.Scene(),wall=new T.InstancedMesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial(),2),actor=new T.Group(),fx=new T.Group();actor.position.set(0,0,0);fx.position.set(0,1,0);const tag=new T.Sprite(new T.SpriteMaterial());actor.add(tag);scene.add(wall,actor,fx);scene.updateMatrixWorld(true);const f={T,g,scene,wall,radius:8,objects:()=>[actor,fx]};let calls=0;const renderer={render(){calls++;assert.equal(actor.visible,false);assert.equal(fx.visible,false);assert.equal(wall.visible,false);assert.equal(scene.getObjectByName('maze-sight-layer').visible,true);}};api.render(f,renderer,null);assert.equal(actor.visible,true);assert.equal(tag.visible,true);assert.equal(fx.visible,true);assert.equal(wall.visible,true);assert.equal(calls,1);assert.ok(api.stats().batches<=7);assert.throws(()=>api.render(f,{render(){throw Error('gpu');}},null));assert.equal(actor.visible,true);api.reset();assert.equal(scene.getObjectByName('maze-sight-layer'),undefined);});

test('視野合批於移牆或換層都清除矩陣緩衝區，借用來源貼圖不被釋放',()=>{
 const ctx=vm.createContext({MazeSightCore:C,performance:{now:()=>1000}});vm.runInContext(readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),ctx);
 const {hw,vw}=maze(3,3),scene=new T.Scene(),map=new T.Texture(),wall=new T.InstancedMesh(new T.BoxGeometry(1,3,1),new T.MeshLambertMaterial({map}),2),extra=new T.InstancedMesh(new T.BoxGeometry(1,1,1),new T.MeshLambertMaterial({map}),2),wallRoot=new T.Group(),floorRoot=new T.Group();wallRoot.add(extra);wall.add(wallRoot);scene.add(wall,floorRoot);
 const g={mazeW:3,mazeH:3,cell:4,wallH:3,wallT:.3,wallBoxes:[],hWalls:hw,vWalls:vw,view:'tp',px:-4,pz:0},f={T,g,scene,wall,atmosphere:{wallRoot,floorRoot},radius:8,objects:()=>[],force:true};let mapDisposed=0,sourceDisposed=0;map.addEventListener('dispose',()=>mapDisposed++);wall.addEventListener('dispose',()=>sourceDisposed++);
 function watch(){const counts=new Map();scene.getObjectByName('maze-sight-layer').traverse(o=>{for(const resource of [o.isInstancedMesh?o:null,o.geometry,o.material])if(resource&&!counts.has(resource)){counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)+1));}});return counts;}
 ctx.MazeSight.update(f);const first=watch();const nextWall=new T.InstancedMesh(wall.geometry,wall.material,2);scene.add(nextWall);ctx.MazeSight.update({...f,wall:nextWall});for(const n of first.values())assert.equal(n,0,'the replaced clones stay alive until the new layer has drawn');
 const renderer={render(){}};for(let frame=0;frame<2;frame++)ctx.MazeSight.render({...f,wall:nextWall},renderer,null);for(const n of first.values())assert.equal(n,1);
 const second=watch();for(const resource of second.keys())resource.dispose();ctx.MazeSight.reset();ctx.MazeSight.reset();for(const n of second.values())assert.equal(n,1,'外部場景已釋放時不得二次清理');assert.equal(mapDisposed,0);assert.equal(sourceDisposed,0);assert.equal(scene.getObjectByName('maze-sight-layer'),undefined);
 for(const mesh of [wall,nextWall,extra])mesh.dispose();wall.geometry.dispose();wall.material.dispose();extra.geometry.dispose();extra.material.dispose();map.dispose();
});

test('the per-frame sight pass allocates no vectors or coordinate objects, and index reuses one frame and object list',()=>{
  const src=readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
  const filter=src.slice(src.indexOf('  function filter('),src.indexOf('  function before('));assert.doesNotMatch(filter,/new /);
  assert.doesNotMatch(src,/function xy\(/);assert.doesNotMatch(src.slice(src.indexOf('function update('),src.indexOf('  function hide(')),/new T\.(?:Matrix4|Quaternion|Vector3|Color)/);
  const frame=html.slice(html.indexOf('function sightFrame()'),html.indexOf('function renderMaze()'));assert.match(frame,/const f=sightState\|\|=/);assert.doesNotMatch(frame,/return \{|new Set|objects:\(\)=>/);
  assert.match(html,/function sightObjects\(\)\{sightList\.length=0;/);
});

test('the owl overview unmasks the whole maze without erasing explored memory or the built fog layer',()=>{
  let now=1000;const ctx=vm.createContext({MazeSightCore:C,performance:{now:()=>now}});vm.runInContext(readFileSync(new URL('../assets/maze-sight.js',import.meta.url),'utf8'),ctx);const api=ctx.MazeSight;
  const {hw,vw}=maze(9,9);const g={mazeW:9,mazeH:9,cell:4,wallH:3,wallT:.3,wallBoxes:[],hWalls:hw,vWalls:vw,view:'tp',px:-16,pz:-16};
  const scene=new T.Scene(),wall=new T.InstancedMesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial(),2),actor=new T.Group();actor.position.set(16,0,16);scene.add(wall,actor);scene.updateMatrixWorld(true);
  const frame=extra=>({T,g,scene,wall,radius:2,force:true,objects:()=>[actor],...extra});
  api.update(frame());for(const [x,z]of [[-12,-16],[-8,-16],[-4,-16]]){g.px=x;g.pz=z;now+=200;api.update(frame());}
  const explored=api.stats().seen;assert.ok(explored>5);assert.equal(api.visible(16,16),false,'the far corner is fogged before the flight');
  const layer=scene.getObjectByName('maze-sight-layer');
  for(let i=0;i<5;i++){now+=200;api.render(frame({overview:true}),{render(){assert.equal(actor.visible,true,'nothing is hidden during the flight');assert.equal(wall.visible,true);}},null);}
  assert.equal(api.active(),false);assert.equal(api.visible(16,16),true);assert.equal(api.cellVisible(8,8),true,'the minimap and other systems see the whole maze');
  assert.ok(api.stats(),'memory is kept');assert.ok(api.stats().seen>=explored,'and still grows during the flight');
  assert.equal(scene.getObjectByName('maze-sight-layer'),layer,'the fog layer is kept, so no shader is rebuilt on landing');
  now+=200;api.update(frame());assert.equal(api.active(),true);assert.ok(api.stats().seen>=explored,'landing restores the explored map');assert.equal(api.visible(16,16),false,'unexplored corners are fogged again');
  const shop=frame({fullVision:true});api.update(shop);assert.equal(api.stats(),null,'shops still clear the fog entirely');
});
