import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),T=require('../lib/three.min.js'),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),R=require('../story/tower-hero-growth.js'),X=require('../story/tower-expedition-core.js'),V=require('../story/tower-characters.js'),N=require('../story/tower-narrative.js'),Q=require('../story/tower-combat-readability.js');
const source=readFileSync(new URL('../story/tower-party-runtime.js',import.meta.url),'utf8');
function fixture(strategy='survive',extra=false){
  let run=H.enable(P.enable(C.newRun({seed:71,name:'安全站位'}),'chef').run).run;run.floor=84;run.floorsCleared=15;run.chronicle=N.newChronicle(84);P.advance(run);
  // Spatial fixtures use valid seeded loadouts. The recruitment transaction is
  // covered elsewhere; this fixture controls only the already-present roster.
  const jobs=extra?['archer','swordsman']:['archer'];for(const profession of jobs){const member={id:'spacing:'+profession,profession,sex:'male',level:1,hp:34,cooldown:0,hurtLeft:0};run.party.members.push(member);run.party.joined.push(member.id);H.addMember(run,member);R.state(run).policies[member.id].strategy=strategy;}
  assert.ok(C.validateSave(run));const world=new T.Group(),player=new T.Group(),G={px:0,pz:4,running:true,shifting:false};let blocked=false,paused=false,preparing=false,cooperating=false,hidden=false;const monsters=[{...P.monsterSpecs(run)[0],alive:true,model:new T.Group(),windup:0}];monsters[0].kind='crab';monsters[0].def={...monsters[0].def,ranged:false};monsters[0].model.position.set(0,0,1.5);
  const peers=[],calls=[],env=vm.createContext({TowerPartyCore:P,TowerHeroes:H,TowerHeroGrowth:R,TowerExpedition:X,TowerCharacters:V,TowerHeroVisuals:{dress(){},pose(){}},TowerHeroesRuntime:{create:()=>({reset(){},hud(){},tick(){},engagement:()=>null,cooperating:()=>cooperating,preparing:()=>preparing,wantsSkill:()=>true})},MazeSight:{active:()=>true,visible:()=>!hidden},document:{getElementById:()=>null}});vm.runInContext(source,env);
  const clear=(a,b)=>!blocked&&Math.abs(b.x)<=1.37&&Math.abs(b.z)<=8,ui=env.TowerPartyRuntime.create({THREE:T,G,core:C,text:String,action:()=>'',dialog(){},save(){},toast(){},audio:{},quest(){},dispose(){},damage(){},bind(){},swing(){},run:()=>run,paused:()=>paused,inDungeon:()=>true,world:()=>world,player:()=>player,monsters:()=>monsters,traders:()=>[],cell:(x,y)=>({x:x*4,z:y*4,cx:x,cy:y}),worldToCell:(x,z)=>({x:Math.round(x/4),y:Math.round(z/4)}),makeHero:()=>new T.Group(),makeText:()=>new T.Group(),clear:(x,z,bx,bz)=>!blocked,followClear:clear,
    transact(result){if(!result.ok)return false;run=result.run;return true;},follow(a,dt,speed,stop,target){calls.push(a.id);const p=a.model.position,dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz),step=Math.min(Math.max(0,d-stop),speed*Math.min(dt,.1));if(!step)return false;const next={x:p.x+dx/d*step,z:p.z+dz/d*step};if(!clear(p,next))return false;p.x=next.x;p.z=next.z;return true;}});
  ui.build(()=>.5,new Set());const models=world.children[0].children.filter(m=>m.userData.companionId),archer=models.find(m=>m.userData.companionId==='spacing:archer');archer.position.set(0,0,0);if(extra)models.find(m=>m!==archer).position.set(0,0,-1.2);
  return {ui,G,run,world,archer,models,monsters,calls,step:dt=>ui.tick(dt,1000),block:value=>blocked=value,pause:value=>paused=value,prepare:value=>preparing=value,cooperate:value=>cooperating=value,hide:value=>hidden=value};
}
test('ranged companions retreat to strategy-specific safe spacing, then hold instead of oscillating back',()=>{
  const distances={};for(const strategy of ['attack','support','survive']){const h=fixture(strategy),before=JSON.stringify(h.run);for(let i=0;i<120;i++)h.step(1/60);distances[strategy]=h.archer.position.distanceTo(h.monsters[0].model.position);const held=h.archer.position.clone();for(let i=0;i<30;i++)h.step(1/60);assert.ok(h.archer.position.distanceTo(held)<.001,strategy);assert.equal(JSON.stringify(h.run),before,'spacing must not change saved HP, gear, resources or policy');assert.ok(Math.abs(h.archer.position.x)<=1.37);}
  assert.ok(distances.attack>=2.09);assert.ok(distances.support>=2.99);assert.ok(distances.survive>=3.79);assert.ok(distances.attack<distances.support&&distances.support<distances.survive);
});
test('retreat is bounded at low frame rates and cannot cross walls, overlap a peer or move the player',()=>{
  for(const dt of [.016,1,10]){const h=fixture('survive',true),old=h.archer.position.clone(),G={x:h.G.px,z:h.G.pz},peer=h.models.find(m=>m!==h.archer);h.step(dt);assert.ok(h.archer.position.distanceTo(old)<=.36001);assert.ok(h.archer.position.distanceTo(peer.position)>=1.149);assert.equal(h.G.px,G.x);assert.equal(h.G.pz,G.z);assert.ok(Math.abs(h.archer.position.x)<=1.37);}
  const h=fixture();h.block(true);const old=h.archer.position.clone();h.step(.1);assert.ok(h.archer.position.equals(old));
});
test('pause, preparing, cooperation, manual strategy and hidden enemies never trigger automatic retreat',()=>{
  for(const configure of [h=>h.pause(true),h=>h.prepare(true),h=>h.cooperate(true),h=>h.hide(true)]){const h=fixture();configure(h);const old=h.archer.position.clone();h.step(.1);if(h.calls.length===0)assert.ok(h.archer.position.equals(old));else assert.ok(h.archer.position.z>=old.z,'hidden enemy does not force retreat away from the leader');}
  const manual=fixture('manual');manual.step(.1);assert.ok(manual.archer.position.z>0,'manual strategy follows the normal queue');
});
test('cleared enemies release the retreat hold and resume the established queue',()=>{const h=fixture();for(let i=0;i<100;i++)h.step(.02);const z=h.archer.position.z;h.monsters[0].alive=false;for(let i=0;i<100;i++)h.step(.02);assert.ok(h.archer.position.z>z);assert.ok(h.calls.length>0);});
test('enemy anticipation uses exact melee, guard and ranged windup duration and release feedback',()=>{
  for(const total of [.8,.9,1.1]){const model=new T.Group(),body=new T.Group();body.scale.set(1.2,1.3,.9);model.add(body);model.userData.body=body;const m={alive:true,model,windup:total,windupTotal:total,def:{ranged:total!==.8}},state=Q.update(T,m);assert.equal(state.material.uniforms.progress.value,0);m.windup=total/2;Q.update(T,m);assert.equal(state.material.uniforms.progress.value,.5);const scale=body.scale.clone();Q.update(T,m,{dt:0});assert.ok(body.scale.equals(scale),'paused frame cannot advance anticipation');m.windup=0;m.cueRelease=1;Q.update(T,m,{dt:.01});assert.equal(state.material.uniforms.progress.value,1);assert.ok(state.impact>0&&state.group.visible);Q.update(T,m,{dt:.3});assert.equal(state.group.visible,false);assert.ok(body.scale.equals(state.baseScale));m.windup=total;Q.update(T,m);assert.equal(state.material.uniforms.progress.value,0);Q.update(T,m,{visible:false});assert.equal(state.group.visible,false);Q.update(T,m,{reducedMotion:true});assert.ok(body.scale.equals(state.baseScale));}
});
test('guard anticipation records its unchanged 0.9 seconds and only releases after durable damage',()=>{
  const guard=source.match(/    function guard\(m,dt\)\{[\s\S]*?(?=    function shift\()/)[0],run=P.enable(C.newRun({seed:71}),'chef').run,member={id:'guard-test',profession:'swordsman',hp:34,level:1,cooldown:0,hurtLeft:0};run.party.members.push(member);run.party.joined.push(member.id);const m={...P.monsterSpecs(run)[0],model:new T.Group(),path:[],windup:0,cooldown:0};let accepts=true;
  const env=vm.createContext({root:{},P,H,modern:()=>false,live:()=>true,r:()=>run,actors:[{id:member.id,model:{position:{x:0,z:1}}}],records:()=>run.party.members,heroes:null,guardVoiceLeft:1,ctx:{clear:()=>true,audio:{sfxGuardBlock(){}},toast(){}},commit:()=>accepts});vm.runInContext(guard+'globalThis.guard=guard;',env);env.guard(m,.1);assert.equal(m.windup,.9);assert.equal(m.windupTotal,.9);accepts=false;env.guard(m,.9);assert.equal(m.cueRelease,undefined);m.windup=.9;accepts=true;env.guard(m,.9);assert.equal(m.cueRelease,1);
});
