import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),R=require('../story/tower-hero-growth.js'),N=require('../story/tower-narrative.js');
const fresh=(job='mage',seed=1)=>H.enable(P.enable(C.newRun({seed,name:'成長測試'}),job).run).run;
const valid=r=>assert.ok(C.validateSave(JSON.stringify(r)),'save remains valid');
function awakened(key){const s=H.SKILLS[key]||H.PASSIVES[key];for(let seed=1;seed<20;seed++){const r=fresh(s.job,seed);H.gainXp(r,R.XP.at(-1));if(R.state(r).awakening===key)return r;}throw Error('missing awakening '+key);}
function recruit(r){r.coins=999;return P.recruit(r,P.recruitOffer(r).id).run;}
test('hero reaches ten, companions five; HP scales once; six skill tiers',()=>{let r=recruit(fresh());const id=r.party.members[0].id;H.setHp(r,'hero',10);for(let l=2;l<=10;l++){H.gainXp(r,R.XP[l-1]-H.state(r).xp);assert.equal(H.level(r,'hero'),l);assert.equal(H.hp(r,'hero'),10+3*(l-1));assert.equal(H.level(r,id),Math.min(l,5));assert.equal(R.skillLevel(r,'hero'),l===10?6:Math.min(l,5));valid(r);}assert.equal(H.maxHp(r,'hero'),87);assert.equal(H.maxHp(r,id),58);});
test('four extra skills exactly, choices at 4/6/8 and fixed awakening at ten',()=>{for(const job of Object.keys(H.JOBS)){let r=fresh(job),a=H.actor(r);assert.equal(R.available(r),0);for(const level of [4,6,8]){H.gainXp(r,R.XP[level-1]-H.state(r).xp);assert.equal(R.available(r),1);const s=Object.values(H.PASSIVES).find(s=>s.job===job&&!s.unique&&!H.actor(r).passives.includes(s.id));const choice=R.choose(r,s.id);assert.ok(choice.ok);r=choice.run;assert.equal(R.choose(r,s.id).ok,false);valid(r);}H.gainXp(r,R.XP.at(-1)-H.state(r).xp);a=H.actor(r);assert.equal(a.skills.length+a.passives.length,9);const first=R.state(r).awakening;H.gainXp(r,10000);assert.equal(R.state(r).awakening,first);assert.equal(H.actor(r).skills.length+H.actor(r).passives.length,9);assert.equal(R.available(r),0);valid(r);}});
test('old loadouts retain skills, gear and health when adding growth defaults',()=>{const r=fresh('chef',71),before=structuredClone(H.actor(r));delete H.state(r).growth;const restored=C.validateSave(r);assert.ok(restored);assert.deepEqual(H.actor(restored),before);assert.equal(R.state(restored).quick.length,4);assert.equal(restored.hp,60);});
test('forged choice, duplicate and companion exclusive skill are rejected',()=>{const r=awakened('star_ring');for(const corrupt of [n=>R.state(n).choices.push('not_real'),n=>H.actor(n).skills.push('star_ring'),n=>R.state(n).food.threshold=101,n=>R.state(n).quick.push('heal')]){const b=structuredClone(r);corrupt(b);assert.equal(C.validateSave(b),null);}let n=recruit(fresh());const id=n.party.members[0].id;H.actor(n,id).skills[0]='decisive_slash';assert.equal(C.validateSave(n),null);});
test('six unique actives consume cooldown, retain a valid save, cannot recast',()=>{for(const s of R.actives){let r=awakened(s.id);for(const k in r.party.ingredients)r.party.ingredients[k]=20;r.party.journey.scrap=20;H.setHp(r,'hero',40);r.hunger=20;const result=H.cast(r,s.id);assert.ok(result.ok,s.id+': '+result.message);valid(result.run);assert.equal(H.cast(result.run,s.id).ok,false);}});
test('all learned normal skills work at tier six without NaN',()=>{for(const s of Object.values(H.SKILLS).filter(s=>!s.unique)){let r=fresh(s.job,23);H.gainXp(r,R.XP.at(-1));if(!H.actor(r).skills.includes(s.id)){const choice=R.choose(r,s.id);assert.ok(choice.ok);r=choice.run;}for(const k in r.party.ingredients)r.party.ingredients[k]=40;r.party.journey.scrap=40;H.setHp(r,'hero',20);r.hunger=10;r.equipment.weapon.durability=1;let target='hero';if(s.id==='revive'){r=recruit(r);target=r.party.members[0].id;H.setHp(r,target,0);}const result=H.cast(r,s.id,{targetId:target});assert.ok(result.ok,s.id);valid(result.run);assert.equal(result.effect.level,6);assert.ok(Number.isFinite(result.effect.power));}});
test('moving fortress exactly 100% HP shield, taunt window 15 and shield 300',()=>{let r=awakened('moving_fortress');r.party.ingredients.shell=5;r.party.journey.scrap=5;const res=H.cast(r,'moving_fortress');assert.ok(res.ok);r=res.run;assert.equal(H.buff(r,'barrier').power,H.maxHp(r));assert.equal(H.buff(r,'barrier').left,300);assert.equal(H.buff(r,'fortress').left,15);assert.equal(H.buff(r,'fortify').power,4);H.tick(r,16);assert.equal(H.buff(r,'fortress'),null);assert.equal(H.buff(r,'fortify'),null);assert.equal(H.buff(r,'barrier').left,284);valid(r);});
test('shields retain higher remaining amount, refresh 300 and survive floor advance',()=>{const r=fresh();R.shield(r,'hero',20);H.tick(r,10);R.shield(r,'hero',8);assert.equal(H.buff(r,'barrier').power,20);assert.equal(H.buff(r,'barrier').left,300);P.advance(r);assert.equal(H.buff(r,'barrier').power,20);H.tick(r,300);assert.equal(H.buff(r,'barrier'),null);valid(r);});
test('many flavors requires two distinct recipes and does not trigger on same food',()=>{let r=awakened('many_flavors');H.setHp(r,'hero',10);r.party.meals.stew=3;r.party.meals.broth=2;r=P.eat(r,'stew').run;assert.deepEqual(R.state(r).tastes,['stew']);r=P.eat(r,'stew').run;assert.equal(H.buff(r,'barrier'),null);P.advance(r);r=P.eat(r,'broth').run;assert.equal(H.buff(r,'barrier').power,H.maxHp(r)*.3);assert.equal(H.buff(r,'barrier').left,300);assert.equal(R.state(r).tasteLeft,90);assert.deepEqual(R.state(r).tastes,[]);valid(r);});
test('life covenant protects nearby companion, not distant or hunger damage',()=>{let r=recruit(awakened('life_covenant'));const id=r.party.members[0].id;H.setHp(r,id,5);R.state(r).nearby.hero=['hero',id];const result=P.hurtMember(r,id,500,r.revision);assert.ok(result.ok);r=result.run;assert.equal(H.hp(r,id),1);assert.ok(H.buff(r,'barrier',id));assert.equal(R.state(r).covenant,180);valid(r);let other=recruit(awakened('life_covenant'));const target=other.party.members[0].id;H.setHp(other,target,5);H.hurt(other,target,500,'hunger');assert.equal(H.hp(other,target),0);});
test('unyielding is not resurrection and persists cooldown',()=>{let r=awakened('unyielding');H.setHp(r,'hero',20);const hit=C.takeDamage(r,2);r=hit.run;assert.ok(H.buff(r,'barrier'));assert.equal(R.state(r).defiance,90);valid(r);});
test('artisan imprint requires safe camp, full durability and resources',()=>{let r=awakened('artisan_soul');r.party.journey.scrap=10;const g=r.equipment.weapon;assert.equal(R.imprint(r,'hero',g.id,false).ok,false);const res=R.imprint(r,'hero',g.id,true);assert.ok(res.ok);r=res.run;const mark=R.imprintFor(r,'hero',r.equipment.weapon);assert.equal(mark.left,Math.ceil(g.maxDurability*.2));const before=r.equipment.weapon.durability;H.wear(r,'hero',r.equipment.weapon);assert.equal(r.equipment.weapon.durability,before);assert.equal(R.state(r).imprints.hero.left,Math.ceil(g.maxDurability*.2)-1);valid(r);});
test('manual quick item acts on controlled actor, cooldown prevents duplicate clicks',()=>{let r=recruit(fresh());const id=r.party.members[0].id;H.setHp(r,id,2);r=H.switchActor(r,id).run;const before=r.bag.heal;const result=R.use(r,'heal');assert.ok(result.ok);r=result.run;assert.equal(r.bag.heal,before-1);assert.equal(H.hp(r,id),34);assert.equal(H.hp(r,'hero'),60);assert.equal(R.use(r,'heal').ok,false);valid(r);});
test('auto heal uses lowest HP, respects reserve, threshold, active toggle and interval',()=>{let r=recruit(fresh());const id=r.party.members[0].id;r.bag.heal=5;H.setHp(r,id,8);H.setHp(r,'hero',2);const g=R.state(r);g.policies[id].heal.enabled=true;g.policies.hero.heal.enabled=true;assert.deepEqual(R.autoItems(r),{id,key:'heal'});g.useActive=true;assert.deepEqual(R.autoItems(r),{id:'hero',key:'heal'});r=R.use(r,'heal','hero',true).run;assert.equal(R.state(r).policies.hero.itemLeft,5);assert.equal(r.bag.heal,4);r.bag.heal=2;assert.equal(R.autoItems(r),null);assert.equal(R.use(r,'heal',id,true).ok,false);assert.ok(R.use(r,'heal',id,false).ok);valid(r);});
test('automatic food is shared and consumes only one ration',()=>{let r=recruit(fresh());r.bag.ration=5;r.hunger=15;R.state(r).food.enabled=true;const candidate=R.autoItems(r);assert.equal(candidate.key,'ration');r=R.use(r,candidate.key,candidate.id,true).run;assert.equal(r.bag.ration,4);assert.ok(r.hunger>=60);assert.equal(R.autoItems(r),null);valid(r);});
test('AI never casts unowned skills or consumes materials without permission',()=>{let r=recruit(fresh('healer'));const id=r.party.members[0].id;R.state(r).policies[id].strategy='attack';const choice=R.aiChoice(r,id,['hero',id],true);assert.ok(choice);assert.ok(H.actor(r,id).skills.includes(choice.skill));const p=R.state(r).policies.hero;p.strategy='support';p.materials=false;H.setHp(r,'hero',1);const suggestion=R.aiChoice(r,'hero',['hero',id],false);assert.equal(suggestion,null);p.materials=true;const heal=R.aiChoice(r,'hero',['hero',id],false);if(heal)assert.equal(H.SKILLS[heal.skill].effect,'heal');});
test('dismissal prunes policy, imprint and spatial records',()=>{let r=recruit(fresh());const id=r.party.members[0].id;R.state(r).nearby.hero=['hero',id];R.state(r).imprints[id]={gearId:H.equipment(r,id).weapon.id,left:1};const result=P.dismiss(r,id);assert.ok(result.ok);valid(result.run);assert.equal(R.state(result.run).policies[id],undefined);});
test('quick items keep revision safety and mage timed-item extension',()=>{let r=fresh('mage');H.setHp(r,'hero',2);assert.equal(C.useItem(r,'heal',r.revision+1).ok,false);if(!H.actor(r).passives.includes('extension'))H.actor(r).passives[0]='extension';r.bag.hourglass=2;const use=R.use(r,'hourglass');assert.ok(use.ok);assert.equal(use.run.effects.freeze,25*(1+H.pv(r,'extension')/100));valid(use.run);});
test('relay needs a different ally, expires and reduces outgoing damage briefly',()=>{let r=recruit(awakened('relay_opening'));const id=r.party.members[0].id,enemy=P.monsterSpecs(r)[0].id;R.strikeMultiplier(r,'hero',enemy,null,false);assert.equal(H.state(r).enemy[enemy].relay,6);R.strikeMultiplier(r,'hero',enemy,null,true);assert.equal(H.state(r).enemy[enemy].relay,6);assert.equal(R.strikeMultiplier(r,id,enemy,null,true),1.6);assert.equal(H.state(r).enemy[enemy].relayWeak,4);H.tick(r,4);assert.equal(H.state(r).enemy[enemy].relayWeak,0);valid(r);});
test('twin stars counts each cast once, not each area target',()=>{const r=awakened('twin_stars'),a=H.actor(r),s=Object.values(H.SKILLS).find(s=>a.skills.includes(s.id)&&s.attack),enemy=P.monsterSpecs(r)[0].id;for(let cast=1;cast<=3;cast++){a.pending={id:s.id,left:3,targets:[],damage:10,worn:false};const before=R.state(r).echo;assert.equal(R.strikeMultiplier(r,'hero',enemy,s,true),cast===3?1.45:1);assert.equal(R.state(r).echo,(before+1)%3);assert.equal(R.strikeMultiplier(r,'hero',enemy,s,true),cast===3?1.45:1);assert.equal(R.state(r).echo,(before+1)%3);}valid(r);});
