import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),R=require('../story/tower-hero-growth.js'),T=require('../lib/three.min.js'),A=require('../story/tower-encounter-alert.js'),UI=require('../story/tower-team-tactics.js');
const fresh=()=>H.enable(P.enable(C.newRun({seed:1,name:'測試'}),'mage').run).run;
test('XP thresholds reduced by one quarter, rewards unchanged and first level boundary',()=>{assert.deepEqual(R.XP,[0,525,1350,2625,4350,6450,9150,12450,16425,21075]);const r=fresh();H.gainXp(r,70);assert.equal(H.state(r).xp,70);assert.equal(H.level(r),1);H.gainXp(r,454);assert.equal(H.level(r),1);H.gainXp(r,1);assert.equal(H.level(r),2);assert.ok(C.validateSave(r));});
test('legacy XP migrates once while preserving level, equipment, HP and learned skills',()=>{const r=fresh();H.gainXp(r,1350);const before=structuredClone(r);delete H.state(r).xpScale;H.state(r).xp=135;const restored=C.validateSave(r);assert.ok(restored);assert.equal(H.state(restored).xp,1350);assert.equal(H.level(restored),3);assert.deepEqual(H.actor(restored),H.actor(before));assert.deepEqual(restored.equipment,before.equipment);assert.equal(restored.hp,before.hp);assert.deepEqual(C.validateSave(restored),restored);const corrupt=structuredClone(restored);H.state(corrupt).xpScale=20;assert.equal(C.validateSave(corrupt),null);});
test('three strategies preserve active actor and automatic item policy and survive save',()=>{let r=fresh();r.coins=999;r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id,before=structuredClone(R.state(r).policies[id]);assert.equal(Object.keys(R.STRATEGIES).length,3);for(const strategy of Object.keys(R.STRATEGIES)){const result=R.setStrategy(r,id,strategy);assert.ok(result.ok);r=C.validateSave(result.run);assert.ok(r);assert.equal(R.state(r).policies[id].strategy,strategy);assert.deepEqual(R.state(r).policies[id].heal,before.heal);assert.equal(H.state(r).active,'hero');}assert.equal(R.setStrategy(r,'missing','attack').ok,false);assert.equal(R.setStrategy(r,id,'invalid').ok,false);});
function clicks(){let time=0,seq=0,ready=true;const pending=new Map(),calls=[];const g=UI.gesture({single:id=>calls.push(['single',id]),double:id=>calls.push(['double',id]),ready:()=>ready,now:()=>time,schedule:fn=>{pending.set(++seq,fn);return seq;},cancel:id=>pending.delete(id)});return {g,calls,advance(ms,flush=false){time+=ms;if(flush)for(const [id,fn]of pending){pending.delete(id);fn();}},block(){ready=false;}};}
test('single tap waits and rapid same-actor double tap switches only once',()=>{const q=clicks();q.g.activate('hero');assert.deepEqual(q.calls,[]);q.advance(100);q.g.activate('hero');q.advance(320,true);assert.deepEqual(q.calls,[['double','hero']]);q.g.activate('other');q.advance(320,true);assert.deepEqual(q.calls.at(-1),['single','other']);});
test('different actors are not a double tap; keyboard, readiness and reset are safe',()=>{const q=clicks();q.g.activate('hero');q.advance(100);q.g.activate('other');q.advance(320,true);assert.deepEqual(q.calls,[['single','other']]);q.g.activate('hero',true);assert.deepEqual(q.calls.at(-1),['single','hero']);q.g.activate('other');q.g.clear();q.advance(320,true);assert.equal(q.calls.length,2);q.g.activate('other');q.block();q.advance(320,true);assert.equal(q.calls.length,2);});
test('encounter visual rearms but voice only once across floors, resets for new session',()=>{const world=new T.Group(),player=new T.Group(),camera=new T.PerspectiveCamera();let voices=0;const a=A.create({THREE:T,world:()=>world,player:()=>player,camera:()=>camera,voice:()=>voices++});a.update(true,.05);assert.equal(voices,1);assert.ok(a.state().visible);assert.equal(world.children.length,1);const marker=world.children[0];assert.equal(marker.children.length,2);assert.equal(marker.children[0].material.color.getHex(),0xff3448);a.update(false,5);assert.equal(a.state().visible,false);a.update(true,.05);assert.equal(voices,1);assert.equal(world.children[0],marker);let disposed=0;marker.traverse(p=>p.geometry?.addEventListener('dispose',()=>disposed++));a.clearVisual();assert.equal(disposed,2);assert.equal(world.children.length,0);a.update(true,.05);assert.equal(voices,1);a.resetSession();a.update(true,.05);assert.equal(voices,2);});
test('first person places alert ahead of camera and returns over player in third person',()=>{const world=new T.Group(),player=new T.Group(),camera=new T.PerspectiveCamera();camera.position.set(5,3,2);player.position.set(1,0,4);let fp=true;const a=A.create({THREE:T,world:()=>world,player:()=>player,camera:()=>camera,voice(){},firstPerson:()=>fp});a.update(true,.05);assert.ok(Math.abs(world.children[0].position.z-.7)<1e-8);fp=false;a.update(true,.05);assert.equal(world.children[0].position.x,1);assert.ok(world.children[0].position.y>2.4);a.clearVisual();});
