import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),N=require('../story/tower-narrative.js'),D=require('../story/tower-dungeons.js');
const fresh=(job='swordsman',seed=31415)=>H.enable(P.enable(C.newRun({seed,name:'遠征者'}),job).run).run;
function floor(r,f){r.floor=f;r.floorsCleared=99-f;r.chronicle=N.newChronicle(f);r.expedition=D.newExpedition();r.claimed=[];r.defeatedMonsters=[];r.monsterStuns={};P.advance(r);return r;}
test('all eleven enemies can retain damage, poise, effects and one area-skill hit after reload',()=>{
  const seed=Array.from({length:500},(_,i)=>i+1).find(s=>C.floorConfig(1,s).monsterCount===11&&H.draft(s,'swordsman','hero').skills.includes('whirlwind'));
  assert.ok(seed);let r=floor(fresh('swordsman',seed),1);const roster=P.monsterSpecs(r);assert.equal(roster.length,11);
  const durability=r.equipment.weapon.durability;r=H.cast(r,'whirlwind').run;
  for(const monster of roster){const hit=H.strike(r,monster.id,{skillId:'whirlwind'});assert.ok(hit.ok,monster.id);r=hit.run;assert.ok(hit.effect.hp>0);r.party.poise[monster.id]=3;H.state(r).enemy[monster.id]={slow:4,slowPower:.3};assert.ok(C.validateSave(JSON.stringify(r)),monster.id);}
  assert.equal(H.actor(r).pending.targets.length,11);assert.equal(Object.keys(r.party.health).length,11);assert.equal(r.equipment.weapon.durability,durability-1);
  const saved=C.validateSave(JSON.stringify(r));assert.deepEqual(saved,r);assert.equal(H.strike(saved,'monster-10',{skillId:'whirlwind'}).ok,false,'A saved cast cannot hit the same target twice');
  for(const id of ['monster-11','monster-01','monster--1','monster-1.5','__proto__']){
    assert.equal(C.validMonsterId(id),false);
    for(const field of ['health','poise']){const bad=structuredClone(r);bad.party[field]={[id]:1};assert.equal(C.validateSave(bad),null);}
    const bad=structuredClone(r);bad.party.loadouts.enemy={[id]:{slow:1}};assert.equal(C.validateSave(bad),null);
    const pending=structuredClone(r);H.actor(pending).pending.targets=[id];assert.equal(C.validateSave(pending),null);
  }
});
test('six professions, 36 actives, 18 passives and 17 distinct pieces',()=>{assert.equal(Object.keys(H.GEAR).length,17);for(const job of Object.keys(H.JOBS)){const skills=Object.values(H.SKILLS).filter(s=>s.job===job);assert.equal(skills.length,6);assert.equal(Object.values(H.PASSIVES).filter(s=>s.job===job).length,3);assert.equal(skills.filter(s=>s.attack).length,['mage','swordsman'].includes(job)?3:2);skills.forEach(s=>assert.equal(s.power.length,5));}});
test('random loadouts are legal, stable and survive JSON without rerolls',()=>{for(const job of Object.keys(H.JOBS))for(let seed=1;seed<150;seed++){const r=fresh(job,seed),a=H.actor(r);assert.equal(a.skills.length,3);assert.equal(a.passives.length,2);assert.ok(a.skills.some(s=>H.SKILLS[s].attack));assert.deepEqual(C.validateSave(JSON.stringify(r)),r);assert.deepEqual(H.draft(seed,job,'hero').skills,a.skills);}});
test('switch preserves separate health, gear, hurt time and skill cooldowns',()=>{let r=fresh('mage');r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id;H.setHp(r,'hero',22);H.actor(r).cooldowns[H.actor(r).skills[0]]=7;H.actor(r).hurt=1.5;const weapon=r.equipment.weapon.id;r=H.switchActor(r,id,r.revision).run;assert.equal(r.hp,34);assert.notEqual(r.equipment.weapon.id,weapon);assert.equal(H.switchActor(r,'hero').ok,false);H.tick(r,1);r=H.switchActor(r,'hero').run;assert.equal(r.hp,22);assert.equal(r.equipment.weapon.id,weapon);assert.equal(H.actor(r).hurt,.5);assert.equal(H.actor(r).cooldowns[H.actor(r).skills[0]],6);assert.deepEqual(C.validateSave(r),r);assert.equal(H.followerRecords(r).length,1);});
test('two handed weapons return shield, reject wrong class, transfers never duplicate',()=>{let r=fresh();r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id,g=C.createGear('greatsword',99,r.seed,'test');r=C.grantGear(r,g).run;const before=H.allGear(r).length;r=H.equip(r,'hero',g.id).run;assert.equal(r.equipment.shield,null);assert.equal(H.allGear(r).length,before);assert.equal(H.equip(r,'hero',r.gearBag.find(g=>g.slot==='shield').id).ok,false);r=H.equip(r,id,g.id).run;assert.equal(r.equipment.weapon,null);assert.equal(H.equipment(r,id).weapon.id,g.id);assert.equal(H.allGear(r).filter(x=>x.id===g.id).length,1);assert.ok(C.validateSave(r));const bad=C.createGear('spellbook',99,r.seed,'wrong');r=C.grantGear(r,bad).run;assert.equal(H.equip(r,'hero',bad.id).ok,false);});
test('full bag does not lose displaced gear or mutate original on failed swap',()=>{let r=fresh();const g=C.createGear('greatsword',99,r.seed,'big');r=C.grantGear(r,g).run;for(let i=0;i<23;i++)r=C.grantGear(r,C.createGear('longsword',99,r.seed,'bag'+i)).run;const old=JSON.stringify(r);assert.equal(H.equip(r,'hero',g.id).ok,false);assert.equal(JSON.stringify(r),old);});
test('attack skills require a paid cast, each target once, wear once per cast',()=>{let r=floor(fresh(),64);const skill=H.actor(r).skills.find(id=>H.SKILLS[id].attack),spec=P.monsterSpecs(r);assert.ok(spec.length>1);assert.equal(H.strike(r,spec[0].id,{skillId:skill}).ok,false);r=H.cast(r,skill).run;const durability=r.equipment.weapon.durability;r=H.strike(r,spec[0].id,{skillId:skill}).run;assert.equal(H.strike(r,spec[0].id,{skillId:skill}).ok,false);r=H.strike(r,spec[1].id,{skillId:skill}).run;assert.equal(r.equipment.weapon?.durability??0,durability-1);assert.equal(H.cast(r,skill).ok,false);assert.ok(C.validateSave(r));});
test('all 36 skills execute and preserve valid saves, costs and cooldowns',()=>{for(const s of Object.values(H.SKILLS)){let r=fresh(s.job),a=H.actor(r);if(!a.skills.includes(s.id)){const other=Object.values(H.SKILLS).filter(v=>v.job===s.job&&v.id!==s.id);const companion=other.find(v=>v.attack!==s.attack);a.skills=[s.id,companion.id,...other.filter(v=>v!==companion&&(s.job!=='healer'||['herbal_heal','revive'].includes(v.id))).slice(0,1).map(v=>v.id)];if(s.job==='healer'&&!a.skills.some(k=>['herbal_heal','revive'].includes(k)))a.skills[2]='herbal_heal';a.cooldowns=Object.fromEntries(a.skills.map(k=>[k,0]));}for(const k of Object.keys(r.party.ingredients))r.party.ingredients[k]=30;H.setHp(r,'hero',20);r.hunger=20;r.equipment.weapon.durability=1;if(s.effect==='revive'){r=P.recruit(r,P.recruitOffer(r).id).run;const m=r.party.members[0];H.setHp(r,m.id,0);H.setHp(r,'hero',20);const result=H.cast(r,s.id,{targetId:m.id});assert.ok(result.ok,s.id);assert.ok(C.validateSave(result.run),s.id);continue;}assert.ok(C.validateSave(r),s.id+' before');const result=H.cast(r,s.id);assert.ok(result.ok,s.id+': '+result.message);assert.ok(C.validateSave(result.run),s.id+' after');assert.ok(H.actor(result.run).cooldowns[s.id]>0);for(const[k,v]of Object.entries(s.cost))assert.equal(result.run.party.ingredients[k],30-v);}});
test('per actor two second immunity, barriers and automatic survivor switch',()=>{let r=fresh();r=P.recruit(r,P.recruitOffer(r).id).run;H.setHp(r,'hero',1);H.setBuff(r,'hero','barrier',10,30);let result=C.takeDamage(r,10);assert.equal(result.effect.damage,0);r=result.run;H.actor(r).buffs=[];r.bag.feather=0;result=C.takeDamage(r,100);assert.equal(result.effect.switched,true);assert.equal(H.hp(result.run,'hero'),0);assert.notEqual(H.state(result.run).active,'hero');assert.equal(result.run.status,'playing');assert.ok(C.validateSave(result.run));});
test('level gain preserves active companion HP and rejects corrupt inventory/loadout',()=>{let r=fresh();r=P.recruit(r,P.recruitOffer(r).id).run;r=H.switchActor(r,r.party.members[0].id).run;const before=r.hp;H.gainXp(r,180);assert.equal(H.level(r),3);assert.equal(r.hp,before+12);assert.ok(C.validateSave(r));const corrupt=structuredClone(r);corrupt.gearBag.push(r.equipment.weapon);assert.equal(C.validateSave(corrupt),null);H.actor(r).skills[0]='not-a-skill';assert.equal(C.validateSave(r),null);});
test('all attack skills at all five levels leave valid bounded combat state',()=>{for(const s of Object.values(H.SKILLS).filter(s=>s.attack))for(let level=1;level<=5;level++){let seed=1;while(!H.draft(seed,s.job,'hero').skills.includes(s.id))seed++;let r=floor(fresh(s.job,seed),64);H.state(r).level=level;const spec=P.monsterSpecs(r)[0];const cast=H.cast(r,s.id);assert.ok(cast.ok,s.id);const hit=H.strike(cast.run,spec.id,{skillId:s.id});assert.ok(hit.ok,s.id);assert.ok(C.validateSave(hit.run),s.id+' level '+level);assert.ok(hit.effect.damage>0);assert.ok((hit.run.party.poise[spec.id]||0)<=5);}});
test('only an actually owned daylight skill enables the lighting shortcut',()=>{const L=require('../story/tower-lighting-core.js');let missing=1;while(H.draft(missing,'mage','hero').skills.includes('daylight'))missing++;const r=fresh('mage',missing);assert.equal(L.canCast(r),false);assert.equal(L.daylight(r).ok,false);let owning=1;while(!H.draft(owning,'mage','hero').skills.includes('daylight'))owning++;const result=L.daylight(fresh('mage',owning));assert.ok(result.ok);assert.equal(result.run.party.light.daylight,600);assert.equal(H.actor(result.run).cooldowns.daylight,600);assert.ok(C.validateSave(result.run));});
test('new merchants sell all new catalog pieces and never replace legacy stock',()=>{const E=require('../story/tower-encounters.js'),kinds=new Set();for(let seed=1;seed<=100;seed++){let r=fresh('chef',seed);r.coins=9999;for(const merchant of E.merchantOffers(99,seed,true)){merchant.gear.forEach(o=>kinds.add(o.kind));for(const item of merchant.gear){const bought=E.buyMerchantGear(r,merchant.id,item.kind,r.revision);assert.ok(bought.ok,item.kind);assert.ok(C.validateSave(bought.run));assert.equal(E.buyMerchantGear(bought.run,merchant.id,item.kind).ok,false);}}assert.ok(E.merchantOffers(99,seed).every(m=>m.gear.every(g=>['helmet','armor','shield','bat','pan','staff'].includes(g.kind))));}assert.deepEqual([...kinds].sort(),Object.keys(H.GEAR).sort());});
test('dismissal returns equipment and clears taunts targeting the removed person',()=>{let r=fresh('mage');r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id,count=H.allGear(r).length;H.state(r).enemy['monster-0']={tauntId:id,tauntLeft:4};const result=P.dismiss(r,id);assert.ok(result.ok);assert.ok(C.validateSave(result.run));assert.equal(H.allGear(result.run).length,count);assert.equal(H.state(result.run).enemy['monster-0'].tauntId,undefined);});
test('tool refill starts when spent, never restores the consumed tool on the next frame',()=>{let seed=1;while(!H.draft(seed,'smith','hero').passives.includes('tool_supply'))seed++;const r=fresh('smith',seed);H.tick(r,.01);assert.equal(r.engine.shovels,1);H.tick(r,100);H.toolSpent(r);assert.equal(r.engine.shovels,0);assert.equal(H.actor(r).tool,90);H.tick(r,89);assert.equal(r.engine.shovels,0);H.tick(r,1);assert.equal(r.engine.shovels,1);assert.ok(C.validateSave(r));});
test('rescue passive prioritizes an owned revive and respects materials and cooldown',()=>{let seed=1;while(!H.draft(seed,'healer','hero').passives.includes('rescue')||!H.draft(seed,'healer','hero').skills.includes('revive'))seed++;let r=fresh('healer',seed);r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id;H.setHp(r,id,0);H.actor(r).autoRescue=true;r.party.ingredients.herb=2;assert.deepEqual(H.rescueChoice(r,'hero'),{skill:'revive',target:id});r=H.cast(r,'revive',{targetId:id}).run;assert.ok(H.hp(r,id)>0);assert.equal(r.party.ingredients.herb,0);assert.equal(H.rescueChoice(r,'hero'),null);assert.ok(C.validateSave(r));});
test('same team buff keeps stronger effect without stacking',()=>{const r=fresh();H.setBuff(r,'hero','rally',10,18);H.setBuff(r,'hero','rally',6,5);assert.equal(H.buff(r,'rally').power,18);assert.equal(H.actor(r).buffs.filter(b=>b.id==='rally').length,1);});
test('exploration healing still reaches the main hero while controlling a companion',()=>{const X=require('../story/tower-expedition-core.js');let seed=1;while(X.siteOffer(fresh('healer',seed)).job!=='healer')seed++;let r=fresh('healer',seed);r=P.recruit(r,P.recruitOffer(r).id).run;const id=r.party.members[0].id;H.setHp(r,'hero',10);H.setHp(r,id,10);r=H.switchActor(r,id).run;const result=X.explore(r,X.siteOffer(r).id,'profession');assert.ok(result.ok);assert.equal(H.hp(result.run,'hero'),22);assert.equal(H.hp(result.run,id),20);assert.ok(C.validateSave(result.run));});
test('every skill has readable level units',()=>{for(const s of [...Object.values(H.SKILLS),...Object.values(H.PASSIVES)]){const scale=H.scale(s);assert.ok(scale.label&&scale.unit,s.id);assert.notEqual(scale.unit,'undefined');}});
