import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {provisionTravellers} from './recruit-fixtures.mjs';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),H=require('../story/tower-heroes-core.js'),P=require('../story/tower-party-core.js'),G=require('../story/tower-hero-growth.js'),R=H.ROBOT,L=require('../story/tower-loot.js'),X=require('../story/tower-expedition-core.js'),N=require('../story/tower-narrative.js'),D=require('../story/tower-dungeons.js');
const fresh=(job='robot',seed=123)=>provisionTravellers(H.enable(P.enable(C.newRun({seed,name:'能源核心測試'}),job).run).run);
const valid=r=>assert.deepEqual(C.validateSave(JSON.stringify(r)),r);
function add(run,job,id=job+'-ally',level=1){const m={id,profession:job,sex:'male',level,hp:28+level*6,cooldown:0,hurtLeft:0};run.party.members.push(m);run.party.joined.push(id);H.addMember(run,m);return id;}
function setFloor(run,f){run.floor=f;run.floorsCleared=f>0?99-f:99;run.chronicle=N.newChronicle(f);run.expedition=D.newExpedition();run.claimed=[];run.defeatedMonsters=[];run.monsterStuns={};P.advance(run,{reward:false});return run;}
function owns(run,key,id='hero'){const a=H.actor(run,id),s=H.SKILLS[key];if(!a.skills.includes(key)){const remove=a.skills.find(k=>H.SKILLS[k].attack===s.attack);a.skills=a.skills.map(k=>k===remove?key:k);delete a.cooldowns[remove];a.cooldowns[key]=0;}return run;}
test('optional-module browser saves recognize the same fuel metadata and strict inventory as the complete bundle',()=>{
  const context=vm.createContext({});for(const file of ['story-core.js','tower-narrative.js','tower-side-stories.js','tower-dungeons.js'])vm.runInContext(readFileSync(new URL('../story/'+file,import.meta.url),'utf8'),context);
  const standalone=context.TowerCore;assert.equal(context.TowerHeroes,undefined);assert.equal(context.TowerRobot,undefined);
  for(const key of R.fuelItemIds)assert.deepEqual(JSON.parse(JSON.stringify(standalone.ITEMS[key])),R.FUEL_ITEMS[key]);
  const run=C.newRun({seed:329,name:'舊瀏覽器相容測試'});for(const [index,key]of R.fuelItemIds.entries())run.bag[key]=index+1;
  const restored=standalone.validateSave(JSON.stringify(run));assert.ok(restored);assert.deepEqual(C.validateSave(JSON.stringify(restored)),run);
  const legacy=structuredClone(run);for(const key of R.fuelItemIds)delete legacy.bag[key];const migrated=standalone.validateSave(JSON.stringify(legacy));assert.ok(migrated);for(const key of R.fuelItemIds)assert.equal(migrated.bag[key],0);
  for(const value of [-1,100,1.5,'1']){const bad=structuredClone(run);bad.bag.power_glimmer=value;assert.equal(standalone.validateSave(JSON.stringify(bad)),null);}
  const unknown=structuredClone(run);unknown.bag.unknown_fuel=0;assert.equal(standalone.validateSave(JSON.stringify(unknown)),null);
  const before=JSON.stringify(restored);assert.equal(standalone.useItem(restored,'power_glimmer').ok,false);assert.equal(JSON.stringify(restored),before,'optional module must not consume fuel without robot behavior');
});
test('new robot starts with one removable tier-one core, two exclusive slots, no fuel-stone gifts',()=>{
  const r=fresh();assert.deepEqual(R.CORE_SLOTS,['core1','core2']);assert.equal(r.equipment.core1.kind,'robot_core');assert.equal(r.equipment.core2,null);assert.equal(H.actor(r).robot.fuel,100);assert.equal(H.actor(r).robot.repairClock,0);for(const key of R.fuelItemIds)assert.equal(r.bag[key],0);valid(r);
  const human=fresh('mage');assert.equal(Object.hasOwn(human.equipment,'core1'),false);valid(human);assert.equal(H.canEquip(human,'hero',r.equipment.core1),false);assert.equal(H.canEquip(r,'hero',r.equipment.core1),false);
});
test('five exact core tiers have bounded durability, defense, gates and no attack or random-roll bonuses',()=>{
  assert.deepEqual(R.CORE_DURABILITY,[100,150,200,250,300]);for(let tier=1;tier<=5;tier++){const kind=R.kind('robot_core',tier),d=R.CORES[kind],g=C.createGear(kind,99,123,'tier'+tier,true);assert.equal(d.requiredLevel,[1,3,5,8,10][tier-1]);assert.equal(d.defense,tier);assert.equal(d.damage,0);assert.equal(g.maxDurability,R.CORE_DURABILITY[tier-1]);assert.deepEqual(C.validateGear(g),g);assert.equal(g.bonus,0);assert.equal(R.isPart(g),false);assert.equal(R.isCore(g),true);for(const bad of [{...g,defense:g.defense+1},{...g,maxDurability:g.maxDurability+1},{...g,bonus:1},{...g,forge:{trait:'plated',level:1,reserve:0}},{...g,slot:'armor'}])assert.equal(C.validateGear(bad),null);}
  assert.ok(!H.gearPool(-50).some(R.isCore));
});
test('exploring exactly ten minutes consumes fuel independent of awakening timers without hunger HP loss',()=>{
  const r=fresh();H.actor(r).robot.energyLeft=8;H.actor(r).robot.energyCooldown=30;const hp=r.hp;H.tick(r,300);assert.equal(H.actor(r).robot.fuel,50);assert.equal(H.actor(r).robot.energyLeft,0);H.tick(r,300);assert.equal(H.actor(r).robot.fuel,0);assert.equal(r.hp,hp);assert.equal(R.powered(r),false);assert.equal(H.speed(r),.9*R.EMPTY_SPEED);assert.equal(H.hurt(r,'hero',100,'hunger').effect.damage,0);assert.equal(r.hp,hp);valid(r);
  const fractional=fresh();for(let i=0;i<6000;i++)R.tick(fractional,'hero',.1);assert.equal(H.actor(fractional).robot.fuel,0);valid(fractional);
});
test('pause, maze shifting, dead or ended journeys cannot drain fuel, repair cores or hurt HP',()=>{
  const r=fresh();H.setHp(r,'hero',10);const before=structuredClone(H.actor(r).robot),core=structuredClone(r.equipment.core1);for(const options of [{paused:true},{shifting:true}]){R.tick(r,'hero',60,options);assert.deepEqual(H.actor(r).robot,before);assert.deepEqual(r.equipment.core1,core);assert.equal(r.hp,10);}H.tick(r,4,{paused:true});assert.equal(H.actor(r).robot.fuel,100);assert.equal(r.hp,10);H.setHp(r,'hero',0);R.tick(r,'hero',60);assert.equal(H.actor(r).robot.fuel,100);H.setHp(r,'hero',10);r.status='won';R.tick(r,'hero',60);assert.equal(H.actor(r).robot.fuel,100);
});
test('empty fuel refuses ordinary punches, paid skills and AI without wear, costs or cooldown',()=>{
  const r=owns(fresh(),'parts_restore');H.setHp(r,'hero',10);H.actor(r).robot.fuel=0;const before=JSON.stringify(r);assert.equal(H.strike(r,'monster-0').ok,false);assert.equal(H.cast(r,'parts_restore').ok,false);assert.equal(G.aiChoice(r,'hero',['hero'],true),null);assert.equal(JSON.stringify(r),before);assert.equal(R.lightInfo(r).radius,8);valid(r);
});
test('two mixed-tier cores independently heal each three-second tick and wear only if they actually participate',()=>{
  const r=fresh();H.gainXp(r,G.XP[4]);r.equipment.core2=C.createGear('robot_core_t3',99,r.seed,'mixed');H.setHp(r,'hero',20);H.tick(r,2.9);assert.equal(r.hp,20);assert.equal(r.equipment.core1.durability,100);H.tick(r,.1);assert.equal(r.hp,24);assert.equal(r.equipment.core1.durability,99);assert.equal(r.equipment.core2.durability,199);assert.equal(H.actor(r).robot.repairClock,0);assert.equal(H.stats(r).armor,R.DEFENSE[0]+4);valid(r);
  H.setHp(r,'hero',H.maxHp(r)-1);H.tick(r,3);assert.equal(r.hp,H.maxHp(r));assert.equal(r.equipment.core1.durability,98);assert.equal(r.equipment.core2.durability,199,'second core does not wear after first completes repair');const wear=[r.equipment.core1.durability,r.equipment.core2.durability];H.tick(r,60);assert.deepEqual([r.equipment.core1.durability,r.equipment.core2.durability],wear);valid(r);
});
test('broken or removed cores give no defense or repair; energy-zero cores can repair and permanent light remains',()=>{
  let r=fresh();H.setHp(r,'hero',20);r.equipment.core1.durability=1;H.actor(r).robot.fuel=0;H.tick(r,3);assert.equal(r.hp,21);assert.equal(r.equipment.core1.durability,0);assert.equal(H.stats(r).armor,R.DEFENSE[0]);const light=R.lightInfo(r);H.tick(r,3);assert.equal(r.hp,21);assert.deepEqual(R.lightInfo(r),light);const out=R.unequipCore(r,'hero','core1');assert.ok(out.ok);r=out.run;H.tick(r,3);assert.equal(r.hp,21);assert.deepEqual(R.lightInfo(r),{tier:1,color:R.CORE_COLORS[0],cores:0,mode:'core',radius:6});valid(r);
});
test('core light uses highest installed tier even broken, never boosts fists or changes their grade',()=>{
  const r=fresh();const fists=r.equipment.weapon.kind;for(let tier=1;tier<=5;tier++){const g=C.createGear(R.kind('robot_core',tier),99,r.seed,'light'+tier);g.durability=0;const info=R.coreLight({core1:r.equipment.core1,core2:g});assert.deepEqual(info,{tier,color:R.CORE_COLORS[tier-1]});r.equipment.core2=g;assert.equal(R.lightInfo(r).mode,'core');assert.equal(R.lightInfo(r).cores,2);assert.equal(R.lightInfo(r).radius,12);assert.equal(r.equipment.weapon.kind,fists);assert.equal(H.stats(r).damage,R.DAMAGE[0]*(1+H.pv(r,'fist_drive')/100));}
});
test('repair tick progress, fuel, gear wear and unique core IDs survive save/reload and descending',()=>{
  const r=fresh();H.setHp(r,'hero',20);H.tick(r,2.25);const restored=C.validateSave(JSON.stringify(r));valid(restored);assert.equal(H.actor(restored).robot.repairClock,2.25);H.advance(restored,{reward:false});assert.equal(H.actor(restored).robot.repairClock,2.25);assert.equal(H.actor(restored).robot.fuel,H.actor(r).robot.fuel);H.tick(restored,.75);assert.equal(restored.hp,21);assert.equal(restored.equipment.core1.id,r.equipment.core1.id);assert.equal(restored.equipment.core1.durability,99);valid(restored);
});
test('old robot save gets exactly one starter core and full fuel once without resetting HP, talents, part wear or timers',()=>{
  const r=fresh();H.setHp(r,'hero',23);r.equipment.weapon.durability=9;r.equipment.armor.durability=19;const talents=structuredClone(H.actor(r).skills);H.actor(r).robot.energyLeft=4;H.actor(r).robot.energyCooldown=18;delete r.equipment.core1;delete r.equipment.core2;delete H.actor(r).robot.fuel;delete H.actor(r).robot.repairClock;for(const key of R.fuelItemIds)delete r.bag[key];assert.equal(R.needsMigration(r),true);const migrated=C.validateSave(r);assert.ok(migrated);assert.equal(migrated.hp,23);assert.equal(migrated.equipment.weapon.durability,9);assert.equal(migrated.equipment.armor.durability,19);assert.deepEqual(H.actor(migrated).skills,talents);assert.equal(H.actor(migrated).robot.fuel,100);assert.equal(H.actor(migrated).robot.energyLeft,4);assert.equal(H.actor(migrated).robot.energyCooldown,18);assert.equal(migrated.equipment.core1.kind,'robot_core');assert.equal(R.needsMigration(migrated),false);valid(migrated);const out=R.unequipCore(migrated,'hero','core1');assert.ok(out.ok);const again=C.validateSave(out.run);assert.equal(again.equipment.core1,null);assert.equal(again.gearBag.length,1);assert.equal(R.needsMigration(again),false);valid(again);
});
test('strict robot fuel, clock and core validation rejects malformed, duplicates, human core slots and level cheating',()=>{
  const r=fresh();for(const corrupt of [n=>H.actor(n).robot.fuel=-1,n=>H.actor(n).robot.fuel=101,n=>H.actor(n).robot.fuel='50',n=>H.actor(n).robot.fuel=null,n=>delete H.actor(n).robot.fuel,n=>H.actor(n).robot.repairClock=3,n=>H.actor(n).robot.repairClock=-1,n=>H.actor(n).robot.foo=1,n=>n.equipment.core2=structuredClone(n.equipment.core1),n=>n.gearBag.push(structuredClone(n.equipment.core1)),n=>n.equipment.core2=C.createGear('robot_core_t2',99,n.seed,'level-cheat'),n=>delete n.equipment.core2,n=>n.bag.power_glimmer=100,n=>n.bag.power_starlight=-1]){const bad=structuredClone(r);corrupt(bad);assert.equal(C.validateSave(bad),null);}
  const human=fresh('mage');human.equipment.core1=C.createGear('robot_core',99,human.seed,'human');assert.equal(C.validateSave(human),null);const inactive=fresh('mage');const id=add(inactive,'robot');H.actor(inactive,id).equipment.core2=structuredClone(H.actor(inactive,id).equipment.core1);assert.equal(C.validateSave(inactive),null);
  for(const corrupt of [n=>G.state(n).policies.hero.fuel.reserve=-1,n=>G.state(n).policies.hero.fuel.enabled=1,n=>G.state(n).policies.hero.fuel.threshold=101,n=>G.state(n).policies.hero.fuel.other=1]){const bad=structuredClone(r);corrupt(bad);assert.equal(C.validateSave(bad),null);}
  assert.throws(()=>R.createGear('__proto__',99,123,'invalid'),RangeError);assert.equal(R.isPart('__proto__'),false);assert.equal(R.isCore('constructor'),false);
});
test('power stones fill 25/50/100 with cap, do not heal and fail atomically for full, dead or human actors',()=>{
  for(const [key,amount]of R.fuelItemIds.map(key=>[key,R.FUEL_ITEMS[key].fuel])){const r=fresh();H.actor(r).robot.fuel=10;H.setHp(r,'hero',20);r.bag[key]=2;const before=JSON.stringify(r),out=C.useItem(r,key,r.revision);assert.ok(out.ok,out.message);assert.equal(H.actor(out.run).robot.fuel,Math.min(100,10+amount));assert.equal(out.run.hp,20);assert.equal(out.run.bag[key],1);valid(out.run);assert.equal(JSON.stringify(r),before);assert.equal(G.use(out.run,key).ok,false,'item cooldown');}
  const r=fresh();r.bag.power_glimmer=1;const before=JSON.stringify(r);assert.equal(G.use(r,'power_glimmer').ok,false);assert.equal(JSON.stringify(r),before);const human=fresh('mage');human.bag.power_glimmer=1;assert.equal(G.use(human,'power_glimmer').ok,false);assert.equal(human.bag.power_glimmer,1);
});
test('automatic fuel refill respects actor preference, reserves and cooldown, never wastes recovery medicine on robots',()=>{
  let r=fresh();r.bag.heal=5;r.bag.ration=5;r.bag.power_glimmer=2;H.setHp(r,'hero',10);H.actor(r).robot.fuel=20;let g=G.state(r);g.policies.hero.heal.enabled=true;g.food.enabled=true;g.policies.hero.fuel.enabled=true;r.hunger=0;assert.equal(G.autoItems(r),null);g.useActive=true;assert.deepEqual(G.autoItems(r),{id:'hero',key:'power_glimmer'});const out=G.use(r,'power_glimmer','hero',true);assert.ok(out.ok);r=out.run;assert.equal(H.actor(r).robot.fuel,45);assert.equal(r.bag.heal,5);assert.equal(r.bag.ration,5);assert.equal(G.autoItems(r),null);H.tick(r,5);g=G.state(r);H.actor(r).robot.fuel=10;g.policies.hero.fuel.reserve=1;assert.equal(G.autoItems(r),null);valid(r);
});
test('paused bag refuels consecutively without ticking the combat cooldown, with atomic full/dead/human/stale rejection',()=>{
  let r=fresh();H.actor(r).robot.fuel=0;r.bag.power_glimmer=5;
  G.state(r).policies.hero.itemLeft=1;
  for(const fuel of [25,50,75,100]){
    const before=JSON.stringify(r),out=R.useFuel(r,'power_glimmer');assert.ok(out.ok,out.message);
    assert.equal(JSON.stringify(r),before);r=out.run;assert.equal(H.actor(r).robot.fuel,fuel);
    assert.equal(G.state(r).policies.hero.itemLeft,1,'bag refill never resets or advances live cooldown');valid(r);
  }
  assert.equal(r.bag.power_glimmer,1);const full=JSON.stringify(r);assert.equal(R.useFuel(r,'power_glimmer').ok,false);assert.equal(JSON.stringify(r),full);
  H.actor(r).robot.fuel=10;const stale=JSON.stringify(r);assert.equal(R.useFuel(r,'power_glimmer','hero',r.revision-1).ok,false);assert.equal(JSON.stringify(r),stale);
  assert.equal(G.use(r,'power_glimmer').ok,false,'live quick slot still waits');H.tick(r,1);assert.ok(G.use(r,'power_glimmer').ok,'live cooldown resumes with simulation');
  H.setHp(r,'hero',0);const dead=JSON.stringify(r);assert.equal(R.useFuel(r,'power_glimmer').ok,false);assert.equal(JSON.stringify(r),dead);
  const human=fresh('mage');human.bag.power_glimmer=1;const organic=JSON.stringify(human);assert.equal(R.useFuel(human,'power_glimmer').ok,false);assert.equal(JSON.stringify(human),organic);
});
test('ordinary healing, food, medicine, revive and healer AI exclude robots without spending materials',()=>{
  const robot=fresh();H.setHp(robot,'hero',10);const hp=robot.hp;assert.equal(H.heal(robot,'hero',20),0);assert.equal(robot.hp,hp);robot.party.meals.stew=1;const before=JSON.stringify(robot);assert.equal(P.eat(robot,'stew').ok,false);assert.equal(G.use(robot,'heal').ok,false);assert.equal(G.use(robot,'ration').ok,false);assert.equal(JSON.stringify(robot),before);owns(robot,'parts_restore');const restore=H.cast(robot,'parts_restore');assert.ok(restore.ok);assert.equal(restore.run.hp,28);assert.equal(restore.run.party.journey.scrap,robot.party.journey.scrap-1);valid(restore.run);
  let human=owns(fresh('healer'),'herbal_heal');const id=add(human,'robot');H.setHp(human,id,10);const materials=structuredClone(human.party.ingredients);const cast=H.cast(human,'herbal_heal',{targetId:id,nearby:['hero',id]});assert.equal(cast.ok,false);assert.deepEqual(human.party.ingredients,materials);assert.equal(G.aiChoice(human,'hero',['hero',id],false),null);H.setHp(human,id,0);owns(human,'revive');assert.equal(H.cast(human,'revive',{targetId:id}).ok,false);assert.equal(H.rescueChoice(human,'hero',['hero',id]),null);valid(human);
});
test('core crafting uses existing materials without another smith, is atomic, gated and strictly bag bounded',()=>{
  let r=fresh();const q=R.craftCoreQuote(r,'hero',1,{safe:true});assert.equal(q.allowed,true);assert.equal(q.affordable,true);assert.equal(q.costs.coins,0);const before=structuredClone(r),out=R.craftCore(r,'hero',1,{safe:true},r.revision);assert.ok(out.ok,out.message);r=out.run;assert.equal(r.gearBag[0].kind,'robot_core');assert.equal(r.party.journey.scrap,before.party.journey.scrap-q.costs.scrap);assert.equal(r.party.journey.materials.ironore,before.party.journey.materials.ironore-q.costs.materials.ironore);assert.equal(r.coins,before.coins);assert.notEqual(r.gearBag[0].id,r.equipment.core1.id);assert.equal(R.craftCore(r,'hero',1,{safe:true},before.revision).ok,false);valid(r);
  for(const tier of [0,2,4,6,1.5])assert.equal(R.craftCoreQuote(r,'hero',tier,{safe:true}).allowed,false);assert.equal(R.craftCore(r,'hero',1,{safe:false}).ok,false);const poor=structuredClone(r);poor.party.journey.scrap=0;const saved=JSON.stringify(poor);assert.equal(R.craftCore(poor,'hero',1,{safe:true}).ok,false);assert.equal(JSON.stringify(poor),saved);r.gearBag=Array.from({length:24},(_,i)=>C.createGear('robot_core',99,r.seed,'full'+i));assert.equal(R.craftCore(r,'hero',1,{safe:true}).ok,false);valid(r);
});
test('core equip, transfer, swap and removal preserve identity/wear with exact caps and revision safety',()=>{
  let r=fresh();H.gainXp(r,G.XP[4]);r.gearBag.push(C.createGear('robot_core_t3',99,r.seed,'swap'));r.gearBag[0].durability=17;const id=r.gearBag[0].id,out=R.equipCore(r,'hero',id,'core2');assert.ok(out.ok,out.message);r=out.run;assert.equal(r.equipment.core2.id,id);assert.equal(r.equipment.core2.durability,17);assert.equal(R.equipCore(r,'hero',id,'core2').ok,false);assert.equal(R.equipCore(r,'hero',id,'weapon').ok,false);assert.equal(R.equipCore(r,'hero',id,'core1',r.revision-1).ok,false);r=R.equipCore(r,'hero',id,'core1').run;assert.equal(r.equipment.core2,null);assert.equal(r.gearBag.length,1);assert.equal(new Set(H.allGear(r).map(g=>g.id)).size,H.allGear(r).length);r=R.unequipCore(r,'hero','core1').run;assert.equal(r.equipment.core1,null);assert.equal(r.gearBag.length,2);valid(r);
  const human=add(r,'mage');assert.equal(R.equipCore(r,human,id,'core1').ok,false);r.gearBag=Array.from({length:24},(_,i)=>C.createGear('robot_core',99,r.seed,'fullcore'+i));r.equipment.core1=C.createGear('robot_core',99,r.seed,'installed');const saved=JSON.stringify(r);assert.equal(R.unequipCore(r,'hero','core1').ok,false);assert.equal(JSON.stringify(r),saved);assert.ok(R.equipCore(r,'hero',r.gearBag[0].id,'core1').ok,'full bag swap consumes one and returns one');valid(r);
});
test('dismissed robot retains fuel, tick progress and worn cores; reunion and archived legacy migration do not duplicate kit',()=>{
  let r=fresh('mage',4);const id=add(r,'robot','robot-away');H.actor(r,id).robot.fuel=14;H.actor(r,id).robot.repairClock=2.5;H.equipment(r,id).core1.durability=21;const equipment=structuredClone(H.equipment(r,id));const out=P.dismiss(r,id);assert.ok(out.ok);r=out.run;assert.deepEqual(r.party.travellers[0].loadout.robotResources,{fuel:14,repairClock:2.5});valid(r);const snapshot=r.party.travellers[0].loadout;const member={id,profession:'robot',sex:'male',level:1,xp:0,hp:34,cooldown:0,hurtLeft:0};r.party.members.push(member);H.restoreMember(r,member,snapshot);assert.equal(H.actor(r,id).robot.fuel,14);assert.equal(H.actor(r,id).robot.repairClock,2.5);assert.deepEqual(H.equipment(r,id),equipment);valid(r);
  r.party.members=[];H.removeMember(r,id);const old=r.party.travellers[0].loadout;delete old.robotEquipment.core1;delete old.robotEquipment.core2;delete old.robotResources;assert.equal(R.needsMigration(r),true);const migrated=C.validateSave(r);assert.ok(migrated);assert.equal(migrated.party.travellers[0].loadout.robotEquipment.core1.kind,'robot_core');assert.equal(migrated.party.travellers[0].loadout.robotResources.fuel,100);assert.equal(R.needsMigration(migrated),false);valid(migrated);
});
test('core cannot gain generic forge/imprint bonuses or be dismantled for endlessly duplicated scrap',()=>{
  const r=fresh();add(r,'smith');r.coins=999;const core=r.equipment.core1,before=JSON.stringify(r);for(const trait of Object.keys(X.TRAITS)){assert.equal(X.traitFits(trait,C.GEAR[core.kind]),false);assert.equal(X.forgeQuote(r,core.id,trait),null);assert.equal(X.forge(r,core.id,trait).ok,false);}assert.equal(X.dismantle(r,core.id).ok,false);assert.equal(G.imprint(r,'hero',core.id,true).ok,false);assert.equal(JSON.stringify(r),before);valid(r);
});
test('fuel stones join monster drops only with a living robot, preserve rarity and ground-claim caps',()=>{
  const r=fresh(),spec=P.monsterSpecs(r)[0],power=L.pool(r,spec).filter(e=>R.fuelItemIds.includes(e.key));assert.deepEqual(power.map(e=>e.rarity),['common','uncommon','rare']);assert.ok(power.every(e=>e.quantity===1));assert.ok(!L.pool(fresh('mage'),spec).some(e=>R.fuelItemIds.includes(e.key)));const id='99:monster-0:item';r.defeatedMonsters.push('monster-0');r.party.loot.rolled=['monster-0'];r.party.loot.entries=[{type:'item',key:'power_sunheart',rarity:'rare',quantity:1,id,source:'monster-0',cx:0,cy:0}];valid(r);const out=L.claim(r,id);assert.ok(out.ok);assert.equal(out.run.bag.power_sunheart,1);valid(out.run);r.bag.power_sunheart=99;assert.equal(L.claim(r,id).ok,false);assert.equal(r.party.loot.entries.length,1);
  for(const mutation of [{quantity:2},{rarity:'common'}]){const bad=structuredClone(r);Object.assign(bad.party.loot.entries[0],mutation);assert.equal(C.validateSave(bad),null);}
  for(const key of ['power_starlight','power_sunheart'])assert.equal(C.buy(r,key).ok,false,'high-grade fuel never sold through generic purchase');
});
