import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

const require=createRequire(import.meta.url),T=require('../lib/three.min.js'),Theater=require('../story/tower-story-theater.js');
const source=readFileSync(new URL('../story/tower-story-theater.js',import.meta.url),'utf8');
function hero(){const actor=new T.Group(),body=new T.Mesh(new T.BoxGeometry(.6,.8,.3),new T.MeshLambertMaterial({color:0x345678})),head=new T.Group(),mouth=new T.Mesh(new T.PlaneGeometry(.1,.02),new T.MeshBasicMaterial()),arms=[new T.Group(),new T.Group()],legs=[new T.Group(),new T.Group()];actor.add(body,head,...arms,...legs);head.add(mouth);body.position.y=1;head.position.y=1.7;actor.position.set(7,.35,-9);actor.rotation.set(.2,.5,.1);actor.userData={head,body,armL:arms[0],armR:arms[1],legL:legs[0],legR:legs[1],face:{mouth,eyes:[],rig:head,mood:'hurt',time:120,left:.9},hp:62};actor.userData.owner=actor;actor.userData.face.owner=actor.userData;return actor;}
function resources(model){const all=new Set();model.traverse(n=>{if(n.geometry&&!n.isSprite)all.add(n.geometry);for(const material of Array.isArray(n.material)?n.material:[n.material])if(material){all.add(material);for(const value of Object.values(material))if(value?.isTexture)all.add(value);}});return all;}
function poses(model){const all=[];model.traverse(n=>all.push([n,n.position.toArray(),n.quaternion.toArray(),n.scale.toArray(),n.visible]));return all;}
function assertPoses(all){for(const[n,p,q,s,v]of all){assert.deepEqual(n.position.toArray(),p);assert.deepEqual(n.quaternion.toArray(),q);assert.deepEqual(n.scale.toArray(),s);assert.equal(n.visible,v);}}
function fixture(options={}){const actor=hero(),actors=[],disposed=[];const stage=Theater.create({THREE:T,hero:actor,buildActor(spec){const npc=hero();npc.userData.name=spec.name;actors.push({npc,spec});return npc;},dispose(npc){disposed.push(npc);for(const resource of resources(npc))resource.dispose();},...options});return {stage,actor,actors,disposed};}
function heroEnvironment(){const env=vm.createContext({THREE:T,CharacterSculpt:require('../assets/character-sculpt.js'),CharacterFace:require('../assets/character-face.js'),TowerHeroes:require('../story/tower-heroes-core.js')});env.window=env;const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),start=html.indexOf('function buildCharacter(cd)'),end=html.indexOf('\n}',start)+2;vm.runInContext(html.slice(start,end),env);vm.runInContext(readFileSync(new URL('../story/tower-heroes-visuals.js',import.meta.url),'utf8'),env);vm.runInContext(readFileSync(new URL('../story/tower-characters.js',import.meta.url),'utf8'),env);return env;}
function shapes(model){model.updateMatrixWorld(true);const inverse=model.matrixWorld.clone().invert(),all=[];model.traverse(node=>{if(node.isMesh)all.push({node,matrix:inverse.clone().multiply(node.matrixWorld).elements.slice(),geometry:node.geometry,material:node.material});});return all;}
function assertShapes(model,original){const current=new Map(shapes(model).map(row=>[row.node,row]));for(const row of original){const after=current.get(row.node);assert.ok(after);assert.ok(after.geometry===row.geometry,'geometry unchanged');assert.ok(after.material===row.material,'material unchanged');for(let i=0;i<16;i++)assert.ok(Math.abs(after.matrix[i]-row.matrix[i])<1e-10,row.node.name+' shape moved at '+i);}}

test('module is standalone in browser/CommonJS with no renderer, RAF, timer, network, storage or gameplay writes',()=>{
  const env=vm.createContext({});vm.runInContext(source,env);assert.equal(typeof env.TowerStoryTheater.create,'function');assert.equal(Theater.create({}),null);
  assert.doesNotMatch(source,/requestAnimationFrame\s*\(|set(?:Timeout|Interval)\s*\(|new\s+T\.WebGLRenderer|fetch\s*\(|localStorage|WebSocket|\.clone\(true|source\.clone|original\.clone|\b(?:run|G)\.[\w]+\s*=/);
});
test('manual hero tree remaps circular face/rig references and borrows geometry/material without mutating or disposing the gameplay actor',()=>{
  const f=fixture(),before=poses(f.actor),originalResources=resources(f.actor),counts=new Map();for(const resource of originalResources){counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)+1));}
  const copy=f.stage.hero;assert.notEqual(copy,f.actor);assert.equal(copy.userData.owner,copy);assert.equal(copy.userData.face.owner,copy.userData);assert.equal(copy.userData.face.rig,copy.userData.head);assert.notEqual(copy.userData.head,f.actor.userData.head);assert.equal(copy.userData.face.mouth.parent,copy.userData.head);assert.equal(copy.userData.body.geometry,f.actor.userData.body.geometry);assert.equal(copy.userData.body.material,f.actor.userData.body.material);assert.equal(copy.userData.hp,62);
  f.stage.page({text:'伊芙向你遞來地圖。',page:1});for(let i=0;i<80;i++)f.stage.frame(i/30);assertPoses(before);assert.equal(f.actor.userData.face.time,120);f.stage.dispose();assert.ok([...counts.values()].every(n=>n===0));assertPoses(before);for(const resource of originalResources)resource.dispose();
});
test('ninety-nine-floor opening has the stone altar, visible summoning rings and moving clouds, not subtitles on an empty stage',()=>{
  const f=fixture({floor:99}),scene=f.stage.scene,nodes=[];scene.traverse(n=>nodes.push(n));assert.equal(nodes.filter(n=>n.isLight).length,3);assert.ok(nodes.filter(n=>n.isMesh).length>15);assert.ok(nodes.filter(n=>n.geometry?.type==='TorusGeometry').length>=2);
  const entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),page=f.stage.page({entry,page:0,text:entry.paragraphs[0],title:entry.title});assert.equal(page.text,entry.paragraphs[0]);assert.equal(page.speechAnimation,false);assert.equal(page.target,f.stage.hero);assert.ok(page.shot.goal.isVector3&&page.shot.focus.isVector3);assert.equal(page.scene,scene);
  const ring=nodes.find(n=>n.geometry?.type==='TorusGeometry'),initial=ring.rotation.z;page.frame(4);assert.notEqual(ring.rotation.z,initial);const sceneResources=resources(scene),borrowed=resources(f.actor),counts=new Map();for(const r of sceneResources){counts.set(r,0);r.addEventListener('dispose',()=>counts.set(r,counts.get(r)+1));}assert.ok(f.stage.dispose());assert.equal(f.stage.dispose(),false);for(const[r,count]of counts)assert.equal(count,borrowed.has(r)?0:1);assert.equal(scene.children.length,0);assert.equal(f.stage.page({text:'已結束'}),null);assert.equal(f.stage.frame(8),false);borrowed.forEach(r=>r.dispose());
});
test('only names actually present in the current paragraph produce one story NPC; changing identity disposes the previous NPC exactly once',()=>{
  const f=fixture(),mapping=[['伊芙','scout','female'],['米菈','healer','female'],['洛恩','smith','male'],['星奈','mage','female'],['奧倫','smith','male'],['璃安','healer','female']];
  f.stage.page({text:'旅人尚未說出她的名字。'});assert.equal(f.actors.length,0);
  for(const[name,job,sex]of mapping){const page=f.stage.page({text:name+'正在看著前方。'});assert.deepEqual(f.actors.at(-1).spec,{job,sex,name});assert.equal(page.target,f.actors.at(-1).npc);assert.equal(page.actor,page.target);assert.equal(page.speechAnimation,false);const count=f.actors.length;f.stage.page({text:name+'說：「先聽故事。」'});assert.equal(f.actors.length,count);const models=f.stage.scene.children.filter(n=>n.userData.storyTheaterActor);assert.equal(models.length,2);}
  assert.equal(f.disposed.length,5);const quiet=f.stage.page({text:'牆壁移動，遠處只有光。'});assert.equal(quiet.target,f.stage.hero);assert.equal(f.actors.at(-1).npc.visible,false);assert.equal(f.actors.length,6);f.stage.dispose();assert.equal(f.disposed.length,6);for(const r of resources(f.actor))r.dispose();
});
test('featured actor belongs to the director; only the secondary hero and scenery breathe, without fake mouth motion',()=>{
  const f=fixture(),named=f.stage.page({text:'米菈指向門。'}),npcBefore=poses(named.target),heroMouth=f.stage.hero.userData.face.mouth.scale.toArray();for(let frame=0;frame<120;frame++)f.stage.frame(frame/30);assertPoses(npcBefore);assert.deepEqual(f.stage.hero.userData.face.mouth.scale.toArray(),heroMouth);assert.notEqual(f.stage.hero.userData.body.scale.y,1);
  const featured=f.stage.page({text:'你望向階梯。'}),before=poses(featured.target);f.stage.frame(19);assertPoses(before);f.stage.dispose();for(const r of resources(f.actor))r.dispose();
});
test('every environment is an authored three-light film stage with bounded baked scenery; underground floors keep their own art direction',()=>{
  const fingerprints=new Set(),arts=new Set();for(const environment of Object.keys(Theater.PALETTES)){const f=fixture({environment}),nodes=[];f.stage.scene.traverse(n=>nodes.push(n));assert.equal(nodes.filter(n=>n.isLight).length,3);assert.ok(nodes.filter(n=>n.isMesh).length<=50);const budget=f.stage.scene.userData.storySceneryBudget;assert.ok(budget.drawables<=50,environment+' drawables '+budget.drawables);assert.ok(budget.triangles<=80000,environment+' triangles '+budget.triangles);assert.ok(budget.textures<=5&&budget.textureBytes<1024*1024);assert.ok(nodes.filter(n=>n.isLight).every(light=>!light.castShadow));arts.add(f.stage.scene.userData.storyArtDirection);fingerprints.add(JSON.stringify(nodes.filter(n=>n.isMesh&&!n.userData.borrowedStoryHero).map(n=>[n.geometry.type,n.geometry.attributes.position.count,n.material.type,n.position.toArray()])));f.stage.page({text:'星奈看向那束光。'});const initial=resources(f.stage.scene);for(const time of [-1,0,1,3600,NaN,Infinity])f.stage.frame(time);assert.deepEqual(resources(f.stage.scene),initial);f.stage.dispose();for(const r of resources(f.actor))r.dispose();}
  assert.equal(fingerprints.size,10);assert.equal(arts.size,10);
  for(const[floor,expected,art]of [[-1,'roots','root-waystation'],[-11,'mist','ferry-canal'],[-21,'library','sunken-archive'],[-31,'furnace','geothermal-well'],[-41,'heart','primordial-gate']]){const stage=Theater.create({THREE:T,floor});assert.equal(stage.scene.userData.environment,expected);assert.equal(stage.scene.userData.underworld,true);assert.equal(stage.scene.userData.storyArtDirection,art);const page=stage.page({text:'一段沒有具名旅人的故事。'});assert.equal(page.actor,null);assert.equal(page.target.name,'story-environment-focus');stage.dispose();}
});
test('no NPC builder, unsafe builder return and failed actor creation do not borrow or reparent a gameplay actor',()=>{
  const original=hero(),stage=Theater.create({THREE:T,hero:original,buildActor:()=>original}),before=poses(original);const page=stage.page({text:'伊芙'});assert.equal(page.target,stage.hero);assertPoses(before);assert.equal(original.parent,null);stage.dispose();for(const r of resources(original))r.dispose();
  const bare=Theater.create({THREE:T,floor:40});assert.equal(bare.page({text:'璃安'}).actor,null);bare.dispose();
  const attached=hero(),world=new T.Group();world.add(attached);const attachedBefore=poses(attached),guard=Theater.create({THREE:T,buildActor:()=>attached});assert.equal(guard.hero,null);assert.equal(guard.page({text:'伊芙'}).actor,null);guard.dispose();assert.equal(attached.parent,world);assertPoses(attachedBefore);for(const resource of resources(attached))resource.dispose();
  const fail=Theater.create({THREE:T,buildActor(){throw new Error('unavailable actor');}});assert.equal(fail.hero,null);assert.equal(fail.page({text:'伊芙'}).actor,null);assert.doesNotThrow(()=>fail.dispose());
});
test('archived stories can create an owned default or selected hero without starting gameplay, and release both actor resources once',()=>{
  for(const options of [{},{heroJob:'robot',heroSex:'female',heroName:'旅行者'}]){
    const created=[],disposed=[],stage=Theater.create({THREE:T,hero:null,...options,buildActor(spec){const actor=hero();created.push({actor,spec});return actor;},dispose(actor){disposed.push(actor);for(const resource of resources(actor))resource.dispose();}});
    assert.deepEqual(created[0].spec,{job:options.heroJob||'swordsman',sex:options.heroSex||'male',name:options.heroName||'旅人'});assert.equal(stage.hero,created[0].actor);assert.equal(stage.hero.userData.ownedStoryHero,true);assert.equal(stage.hero.userData.borrowedStoryHero,undefined);const page=stage.page({text:'你站在召喚陣裡。'});assert.equal(page.target,stage.hero);assert.equal(page.speechAnimation,false);stage.page({text:'伊芙向你指路。'});assert.equal(created.length,2);assert.equal(stage.scene.children.filter(n=>n.userData.storyTheaterActor).length,2);assert.equal(stage.scene.children.filter(n=>n.isLight).length,3);
    const counts=new Map();for(const {actor}of created)for(const resource of resources(actor)){counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)+1));}stage.frame(3);stage.dispose();assert.equal(stage.dispose(),false);assert.equal(disposed.length,2);assert.ok([...counts.values()].every(n=>n===1));assert.equal(stage.scene.children.length,0);
  }
});
test('reduced-motion stage keeps all own scenery and secondary actor still across every page, without changing the original hero',()=>{
  const f=fixture({reduced:true}),original=poses(f.actor);for(const text of ['伊芙向你指路。','你站在召喚陣中。','星奈告別。']){const page=f.stage.page({text}),before=poses(f.stage.scene);for(const time of [-1,0,1,60,3600])assert.equal(page.frame(time),true);assertPoses(before);assertPoses(original);}assert.equal(f.stage.frame(NaN),false);f.stage.dispose();for(const resource of resources(f.actor))resource.dispose();
});
test('all nine real professions and both sexes retain their mapped face/rig across idle, loading, silent, suspension and narration playback',()=>{
  const env=heroEnvironment(),Actors=require('../story/tower-cinematic-actors.js'),jobs=Object.keys(env.TowerHeroes.JOBS);assert.equal(jobs.length,9);
  for(const job of jobs)for(const sex of ['male','female']){
    const original=env.TowerHeroVisuals.base(job,env.buildCharacter,'hero',sex),base=poses(original),borrowed=resources(original),stage=Theater.create({THREE:T,hero:original}),copy=stage.hero,page=stage.page({text:'你望向迷宮，前方的石台安靜發光。'}),actor=Actors.create(page),mouth=copy.userData.face.mouth,mouthScale=mouth.scale.toArray(),mouthVisible=mouth.visible,stageResources=resources(stage.scene);
    assert.notEqual(copy.userData.head,original.userData.head);assert.equal(copy.userData.face.rig,copy.userData.head);assert.equal(page.speechAnimation,false);
    for(const state of [{speaking:false,phase:'playing'},{speaking:true,loading:true,phase:'loading'},{speaking:true,phase:'silent'},{speaking:false,phase:'suspended'},{speaking:false,phase:'playing'}]){stage.frame(2.4);actor.sample(2.4,state);assert.deepEqual(mouth.scale.toArray(),mouthScale);assert.equal(mouth.visible,mouthVisible);assertPoses(base);assert.deepEqual(resources(stage.scene),stageResources);}
    actor.restore();stage.dispose();assertPoses(base);for(const resource of borrowed)resource.dispose();
  }
});
test('five named story actors reuse distinct world silhouettes; pivoting groups preserve every authored shape and keep hats, hair and face attached',()=>{
  const env=heroEnvironment(),Actors=require('../story/tower-cinematic-actors.js'),original=env.TowerHeroVisuals.base('mage',env.buildCharacter,'hero','female'),originalPose=poses(original),made=[],fallback=[];
  const stage=Theater.create({THREE:T,hero:original,buildStoryActor(spec){const actor=env.TowerCharacters.buildExplorer(spec.id,{THREE:T});made.push({actor,spec,shapes:shapes(actor),resources:resources(actor)});return actor;},buildActor(spec){fallback.push(spec);return env.TowerHeroVisuals.base(spec.job,env.buildCharacter,spec.name,spec.sex);}}),fingerprints=new Set();
  const expected=[['伊芙','eve','travel-hat-brim'],['米菈','mira','round-double-bun'],['洛恩','rowan','windswept-fringe-root'],['星奈','sena','comet-hairpin-star'],['奧倫','oren','long-pointed-white-beard']];
  for(const[name,id,attachmentName]of expected){
    const page=stage.page({text:name+'指向前方。'}),record=made.at(-1),model=page.target,head=model.userData.cinemaRig.head,attachment=model.getObjectByName(attachmentName);assert.equal(record.spec.id,id);assert.equal(model.userData.explorerId,id);assert.equal(model.userData.storyIdentity,name);assert.equal(head.name,'cinema-head');assert.ok(model.userData.headMesh.parent===head,name+' head mesh attached');assert.ok(model.userData.face.rig===head,name+' face rig attached');assert.ok(attachment.parent===head,name+' attachment attached');assert.ok(model.userData.face.mouth.parent===head,name+' mouth attached');assert.ok(model.userData.armL.parent===model,name+' arm stays separate');const currentResources=resources(model);assert.equal(currentResources.size,record.resources.size);for(const resource of record.resources)assert.ok(currentResources.has(resource));assertShapes(model,record.shapes);
    const posesBefore=poses(model),session=Actors.create(page),local=attachment.position.toArray();model.updateMatrixWorld(true);const before=attachment.getWorldQuaternion(new T.Quaternion());session.sample(2.4,{speaking:false,phase:'playing'});model.updateMatrixWorld(true);assert.ok(attachment.getWorldQuaternion(new T.Quaternion()).angleTo(before)>1e-4,name+' attachment follows head rotation');assert.deepEqual(attachment.position.toArray(),local);session.restore();assertPoses(posesBefore);assertShapes(model,record.shapes);assertPoses(originalPose);
    fingerprints.add(JSON.stringify([...record.resources].filter(resource=>resource.isBufferGeometry).map(resource=>[resource.type,resource.attributes.position.count])));
  }
  assert.equal(fallback.length,0);assert.equal(made.length,5);assert.equal(fingerprints.size,5);const sena=made.find(record=>record.spec.id==='sena').actor;assert.ok(sena.getObjectByName('pocket-telescope'));assert.ok(!stage.hero.getObjectByName('pocket-telescope'));assert.notEqual(sena.userData.headMesh.geometry,stage.hero.userData.headMesh.geometry);stage.dispose();for(const resource of resources(original))resource.dispose();
});
test('Lian keeps the healer silhouette with isolated silver hair and teal clothing materials; original colors and borrowed hero stay untouched',()=>{
  const env=heroEnvironment(),original=env.TowerHeroVisuals.base('healer',env.buildCharacter,'hero','female'),originalPose=poses(original),created=[];
  const stage=Theater.create({THREE:T,hero:original,buildActor(spec){const actor=env.TowerHeroVisuals.base(spec.job,env.buildCharacter,spec.name,spec.sex),colors=new Map([...resources(actor)].filter(resource=>resource.isMaterial&&resource.color).map(mat=>[mat,mat.color.getHex()]));created.push({actor,spec,colors});return actor;}}),page=stage.page({text:'璃安走到石門前。'}),record=created[0],lian=page.target;
  assert.deepEqual(record.spec,{job:'healer',sex:'female',name:'璃安'});assert.equal(lian.userData.storyIdentityPalette,'lian-teal-silver');assert.equal(lian.userData.body.material.color.getHex(),0x337f83);assert.equal(lian.getObjectByName('hair-crown').material.color.getHex(),0xddebe8);assert.notEqual(lian.userData.body.material,original.userData.body.material);assert.notEqual(lian.getObjectByName('hair-crown').material,original.getObjectByName('hair-crown').material);for(const[mat,color]of record.colors)assert.equal(mat.color.getHex(),color);assertPoses(originalPose);
  const all=new Set([...resources(stage.scene),...record.colors.keys()]),counts=new Map();for(const resource of all){counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)+1));}stage.dispose();const borrowed=resources(original);for(const[resource,count]of counts)assert.equal(count,borrowed.has(resource)?0:1);for(const resource of borrowed)resource.dispose();
});
test('story-specific actor builder failures safely use base actors, and unattached scene actors are required even for named identities',()=>{
  for(const result of ['throw','attached']){const world=new T.Group(),unsafe=hero();world.add(unsafe);const before=poses(unsafe),fallback=[];const f=fixture({buildStoryActor(){if(result==='throw')throw new Error('unavailable costume');return unsafe;},buildActor(spec){fallback.push(spec);return hero();}});const page=f.stage.page({text:'星奈'});assert.equal(page.target.userData.storyIdentity,'星奈');assert.deepEqual(fallback,[{job:'mage',sex:'female',name:'星奈'}]);assertPoses(before);assert.equal(unsafe.parent,world);f.stage.dispose();for(const resource of resources(f.actor))resource.dispose();for(const resource of resources(unsafe))resource.dispose();}
});
test('summit approval preview has three actual depth layers, original procedural surfaces, cloth/sky gradients and conservative baked scenery',()=>{
  const stage=Theater.create({THREE:T,floor:99}),scene=stage.scene,set=scene.getObjectByName('story-theater-environment'),nodes=[];set.traverse(n=>nodes.push(n));
  for(const name of ['near','middle','far'])assert.ok(scene.getObjectByName('story-'+name+'-scenery'));
  const budget=scene.userData.storySceneryBudget;assert.ok(budget.drawables<=100);assert.ok(budget.triangles<=80000);assert.equal(budget.drawables,nodes.filter(n=>n.isMesh||n.isPoints).length);assert.equal(budget.textures,4);assert.equal(budget.textureBytes,3*256*256*4+128*128*4);
  const maps=[...resources(set)].filter(r=>r.isTexture);assert.equal(maps.length,4);assert.ok(maps.every(tex=>tex.isDataTexture&&tex.image.width<=256&&tex.image.height<=256));assert.ok(maps.every(tex=>new Set(tex.image.data).size>15));
  const sky=scene.getObjectByName('story-gradient-sky');assert.ok(sky.geometry.attributes.color);assert.equal(sky.material.fog,false);const skyColor=sky.geometry.attributes.color;assert.ok(new Set(skyColor.array).size>10);assert.equal(scene.userData.storyMotionTracks.filter(t=>t.kind==='cloud').length,3);assert.equal(scene.userData.storyMotionTracks.filter(t=>t.name==='story-summit-banner').length,2);
  for(let i=0;i<skyColor.count;i++){assert.ok(skyColor.getZ(i)>skyColor.getY(i));assert.ok(skyColor.getY(i)>skyColor.getX(i));}const ridges=nodes.filter(n=>n.name==='story-layered-mountain-ridge');assert.equal(ridges.length,3);for(const ridge of ridges){const color=ridge.geometry.attributes.color;for(let i=0;i<color.count;i++){assert.ok(color.getY(i)>color.getX(i));assert.ok(color.getY(i)>color.getZ(i));}}assert.equal(scene.fog.color.getHex(),0xb6d8e7);
  assert.ok(nodes.some(n=>n.userData.storyBakedPieces>10));assert.ok(nodes.some(n=>n.material?.isMeshPhongMaterial));for(const n of nodes)if(n.geometry?.attributes?.normal)for(let i=0;i<n.geometry.attributes.normal.count;i++){const a=n.geometry.attributes.normal;assert.ok(Math.abs(Math.hypot(a.getX(i),a.getY(i),a.getZ(i))-1)<1e-5);}
  const opening=stage.page({text:'召喚陣的光芒出現。',page:0}),next=stage.page({text:'伊芙指向前方。',page:1});assert.equal(opening.shot.edition,'preview');assert.equal(opening.shot.fov,56);assert.equal(opening.shot.duration,15);assert.ok(opening.shot.focusTo.isVector3&&opening.shot.goalTo.isVector3);assert.equal(next.shot.fov,48);assert.equal(opening.performance,'reveal');const original=resources(scene);for(let frame=0;frame<1800;frame++)stage.frame(frame/60);assert.deepEqual(resources(scene),original);assert.doesNotMatch(source.slice(source.indexOf('function frame(time)'),source.indexOf('function page(spec')),/\bnew\s|\.map\(|\.filter\(/);stage.dispose();
});
test('every region builds its own layered film set, procedural surfaces, landmarks and editorial cuts instead of a placeholder platform',()=>{
  const landmarks=new Map();
  for(const environment of ['garden','roots','echo','library','mist','frost','clockwork','furnace','heart']){const stage=Theater.create({THREE:T,environment,floor:60}),scene=stage.scene,set=scene.getObjectByName('story-theater-environment'),nodes=[];set.traverse(n=>nodes.push(n));
    assert.equal(scene.userData.cinematicPreview,true);for(const name of ['near','middle','far'])assert.ok(scene.getObjectByName('story-'+name+'-scenery'));
    const budget=scene.userData.storySceneryBudget;assert.equal(budget.drawables,nodes.filter(n=>n.isMesh||n.isPoints).length);assert.ok(budget.drawables<=50&&budget.triangles<=80000);
    assert.ok(Object.isFrozen(set.userData.storyLandmarks)&&set.userData.storyLandmarks.length>=5);landmarks.set(environment,set.userData.storyLandmarks.join());assert.notEqual(set.userData.storyArtDirection,'cloud-summit');
    assert.ok(nodes.some(n=>n.userData.storyBakedPieces>10),'static dressing is baked');assert.ok(nodes.some(n=>n.material?.isMeshPhongMaterial));assert.ok(nodes.some(n=>n.isPoints),'region atmosphere motes');
    assert.ok([...resources(set)].filter(r=>r.isTexture).every(tex=>tex.isDataTexture&&tex.image.width<=256));for(const n of nodes)if(n.geometry?.attributes?.normal&&n.userData.storyBakedPieces)for(let i=0;i<n.geometry.attributes.normal.count;i++){const a=n.geometry.attributes.normal;assert.ok(Math.abs(Math.hypot(a.getX(i),a.getY(i),a.getZ(i))-1)<1e-5);}
    assert.equal(scene.children.filter(n=>n.isLight).length,3);assert.ok(scene.userData.storyMotionTracks.length>=3,environment+' has retained moving props');
    const page=stage.page({text:'光芒出現。'});assert.equal(page.shot.edition,'preview');assert.ok(page.shot.cuts.length>=3&&page.shot.cuts.length<=4);assert.ok(page.shot.cuts.every(c=>c.subjects.every(s=>s==='hero')));
    const original=resources(scene);for(let frame=0;frame<900;frame++)stage.frame(frame/30);assert.deepEqual(resources(scene),original);stage.dispose();assert.equal(scene.children.length,0);}
  assert.equal(new Set(landmarks.values()).size,9);
});
test('every region applies one film material session, restores it before owned actor disposal, and releases it once',()=>{
  const old=globalThis.TowerCinematicLook,events=[];globalThis.TowerCinematicLook={create(){events.push('create');return {apply(model){events.push('apply:'+model.name);model.userData.previewFinish=true;let active=true;return {restore(){if(!active)return false;active=false;delete model.userData.previewFinish;events.push('restore:'+model.name);return true;}};},dispose(){events.push('session-dispose');}};}};
  try{for(const environment of ['cloud','garden','furnace']){events.length=0;const original=hero(),borrowed=resources(original),before=poses(original),stage=Theater.create({THREE:T,hero:original,environment,buildActor(){return hero();},dispose(model){assert.equal(model.userData.previewFinish,undefined);events.push('dispose:'+model.name);for(const resource of resources(model))resource.dispose();}});assert.equal(events[0],'create');assert.equal(original.userData.previewFinish,undefined);stage.page({text:'伊芙'});stage.page({text:'星奈'});stage.dispose();assert.equal(events.filter(e=>e==='create').length,1);assert.equal(events.filter(e=>e==='session-dispose').length,1);assert.equal(events.filter(e=>e.startsWith('restore:')).length,3);assert.ok(events.indexOf('restore:story-伊芙')<events.indexOf('dispose:story-伊芙'));assertPoses(before);for(const resource of borrowed)resource.dispose();}}finally{if(old===undefined)delete globalThis.TowerCinematicLook;else globalThis.TowerCinematicLook=old;}
});
test('only the approved summit has editorial cuts, with bounded chronological data, original fallback and no invented subjects',()=>{
  const f=fixture(),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99);
  for(let page=0;page<3;page++){
    const spec=f.stage.page({entry,page}),cuts=spec.shot.cuts;assert.equal(spec.text,entry.paragraphs[page]);assert.ok(Object.isFrozen(cuts));assert.equal(cuts.length,4);assert.ok(cuts.length<=8);assert.equal(cuts[0].at,0);assert.equal(new Set(cuts.map(c=>c.id)).size,cuts.length);const visible=f.stage.scene.children.filter(n=>n.userData.storyTheaterActor&&n.visible).map(n=>n.userData.storyIdentity||'hero');
    assert.ok(spec.shot.focus.isVector3&&spec.shot.goal.isVector3&&spec.shot.goalTo.isVector3&&spec.shot.focusTo.isVector3);assert.equal(spec.shot.duration,15);
    for(let i=0;i<cuts.length;i++){const cut=cuts[i];assert.ok(Object.isFrozen(cut)&&Object.isFrozen(cut.subjects));if(i)assert.ok(cut.at>cuts[i-1].at);assert.ok(cut.duration>0&&cut.duration<=15);assert.ok(cut.fov>=38&&cut.fov<=64);assert.ok(cut.subjects.length>0);for(const subject of cut.subjects){assert.equal(typeof subject,'string');assert.ok(visible.includes(subject));}for(const key of ['goal','goalTo','focus','focusTo'])assert.ok(cut[key].isVector3&&cut[key].toArray().every(Number.isFinite));assert.ok(cut.goal.distanceTo(cut.goalTo)<1.2,'push stays within its own shot');assert.ok(cut.goal.z>2&&cut.goalTo.z>2,'camera cannot cross the altar or rear columns');}
    if(page===0){assert.deepEqual(cuts.map(c=>c.at),[0,4,8,11.5]);assert.deepEqual(cuts.map(c=>c.id),['summit-establish','summoning-side','traveller-awakens','traveller-question']);assert.ok(cuts[0].goal.y>cuts[1].goal.y+3);assert.ok(cuts[1].goal.x>cuts[2].goal.x+3);assert.ok(cuts[3].goal.distanceTo(spec.target.position)<cuts[2].goal.distanceTo(spec.target.position));assert.deepEqual(visible,['hero']);}else{assert.ok(cuts.some(c=>c.subjects.length===2));assert.ok(cuts.some(c=>c.subjects.length===1&&c.subjects[0]==='伊芙'));}
  }
  const noName=f.stage.page({page:2,text:'你回望石台上的召喚陣。'});assert.ok(noName.shot.cuts.every(c=>c.subjects.every(subject=>subject==='hero')));assert.equal(f.stage.scene.children.find(n=>n.userData.storyIdentity==='伊芙').visible,false);f.stage.dispose();for(const resource of resources(f.actor))resource.dispose();
});
test('every summit cut frames actual profession face heights above mobile captions and keeps columns out of the subject sightline',()=>{
  const env=heroEnvironment(),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),ray=new T.Raycaster(),point=new T.Vector3(),direction=new T.Vector3();
  for(const job of Object.keys(env.TowerHeroes.JOBS))for(const sex of ['male','female']){
    const original=env.TowerHeroVisuals.base(job,env.buildCharacter,'hero',sex),before=poses(original),stage=Theater.create({THREE:T,hero:original,buildStoryActor:spec=>env.TowerCharacters.buildExplorer(spec.id,{THREE:T})});
    for(let page=0;page<3;page++){
      const spec=stage.page({entry,page}),solid=[];stage.scene.getObjectByName('story-theater-environment').traverse(n=>{if(n.isMesh&&!n.material.transparent)solid.push(n);});stage.scene.updateMatrixWorld(true);
      for(const cut of spec.shot.cuts)for(const [width,height,captionTop]of [[1440,900,643],[844,390,205],[568,320,135]])for(const progress of [0,.5,1]){
        const camera=new T.PerspectiveCamera(cut.fov,width/height,.1,100),focus=cut.focus.clone().lerp(cut.focusTo,progress);focus.y+=height<=340?-.24:height<=420?-.13:0;camera.position.copy(cut.goal).lerp(cut.goalTo,progress);camera.lookAt(focus);camera.updateMatrixWorld(true);
        for(const identity of cut.subjects){const actor=stage.scene.children.find(n=>n.userData.storyTheaterActor&&n.visible&&(n.userData.storyIdentity||'hero')===identity),head=actor.userData.headMesh||actor.userData.head;head.getWorldPosition(point);const world=point.clone(),p=point.clone().project(camera),x=(p.x+1)*width/2,y=(1-p.y)*height/2,label=[job,sex,page,cut.id,width,progress,identity].join(':');assert.ok(p.z>-1&&p.z<1,label+' depth');assert.ok(x>16&&x<width-16,label+' horizontal');assert.ok(y>16&&y<captionTop-16,label+' face-caption margin '+y);const top=point.clone();top.y+=.23;assert.ok(top.project(camera).y<.99,label+' face is not top-cropped');direction.copy(world).sub(camera.position);ray.set(camera.position,direction.normalize());ray.far=camera.position.distanceTo(world)-.12;assert.equal(ray.intersectObjects(solid,false).length,0,label+' solid scenery cannot occlude the face');}
      }
    }
    stage.dispose();assertPoses(before);for(const resource of resources(original))resource.dispose();
  }
});
test('only the exact three approved opening paragraphs expose immutable two-actor narrative plans at the existing audio playback rate',()=>{
  const f=fixture(),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),sourceLengths=[24.4,24.24,19.52];
  for(let index=0;index<3;index++){
    const page=f.stage.page({entry,page:index}),plan=f.stage.scene.userData.storyActionPlan;
    assert.ok(Object.isFrozen(page.actorTracks)&&Object.isFrozen(plan));assert.deepEqual(page.actorTracks.map(track=>track.identity),index?['hero','伊芙']:['hero']);assert.equal(plan.pageIndex,index);assert.equal(plan.narrationRate,1.16);assert.equal(plan.sourceDuration,sourceLengths[index]);assert.equal(plan.duration,sourceLengths[index]/1.16);assert.doesNotThrow(()=>JSON.stringify(plan));assert.equal(JSON.stringify(plan).includes('Object3D'),false);
    for(const track of page.actorTracks){assert.equal(track.speechAnimation,false);assert.equal(track.actor.userData.storyTheaterActor,true);assert.ok(Object.isFrozen(track)&&Object.isFrozen(track.beats));assert.equal(track.beats[0].at,0);assert.ok(track.beats.length>=5);let end=0;for(const beat of track.beats){assert.ok(Object.isFrozen(beat));assert.ok(Math.abs(beat.at-end)<1e-12,'no silent acting gaps');assert.ok(beat.duration>.3);end=beat.at+beat.duration;}assert.ok(Math.abs(end-plan.duration)<1e-12,'acting covers the full narration');}
    if(index===0){assert.equal(page.actorTracks[0].beats[0].gesture,'wake');assert.ok(page.actorTracks[0].beats[1].gaze.x<0);assert.ok(Object.isFrozen(page.actorTracks[0].beats[1].gaze));assert.equal(plan.props.length,0);}
    if(index===1){assert.deepEqual(page.shot.cuts.map(cut=>cut.at),[0,4,7.5,13.5]);assert.deepEqual(page.shot.cuts[2].subjects,['hero','伊芙']);assert.equal(plan.props[0].at,11/1.16);assert.equal(plan.props[1].at,15/1.16);}
    if(index===2){const eve=page.actorTracks[1];assert.equal(eve.beats[1].mood,'surprised');assert.equal(eve.beats[2].mood,'reflective');assert.equal(plan.props[0].kind,'copper');}
  }
  for(const spec of [{entry:{...entry,id:'goal:99'},page:0},{entry,page:0,text:'你站在塔頂，等待新的委託。'},{entry,page:3,text:'伊芙仍在塔頂。'},{text:entry.paragraphs[0],page:0}]){assert.equal(f.stage.page(spec).actorTracks,undefined);assert.equal(f.stage.scene.userData.storyActionPlan,null);assert.equal(f.stage.scene.getObjectByName('story-film-prop-prewarm'),undefined);const props=[];f.stage.scene.traverse(node=>{if(node.userData.storyFilmProp)props.push(node);});assert.equal(props.length,0);}
  f.stage.dispose();for(const resource of resources(f.actor))resource.dispose();
  for(const options of [{floor:95},{environment:'garden',floor:99}]){const stage=Theater.create({THREE:T,...options});assert.equal(stage.page({entry,page:0}).actorTracks,undefined);assert.equal(stage.scene.userData.storyActionPlan,null);stage.dispose();}
});
test('paper and copper are page-initialized film props, revealed at text time, attached to hands, and released once without touching gameplay equipment',()=>{
  const env=heroEnvironment(),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),original=env.TowerHeroVisuals.base('swordsman',env.buildCharacter,'hero','female');
  const weapon={...env.TowerHeroes.GEAR.longsword,kind:'longsword',durability:100};env.TowerHeroVisuals.dress(T,original,{weapon},()=>{});const before=poses(original),borrowed=resources(original),stage=Theater.create({THREE:T,hero:original,buildStoryActor:spec=>env.TowerCharacters.buildExplorer(spec.id,{THREE:T})}),owned=new Set(),counts=new Map();
  const remember=()=>{for(const resource of resources(stage.scene))if(!borrowed.has(resource)&&!owned.has(resource)){owned.add(resource);counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)+1));}};
  stage.page({entry,page:0});remember();assert.equal(stage.scene.getObjectByName('story-film-map'),undefined);const warm=stage.scene.getObjectByName('story-film-prop-prewarm');assert.equal(warm.children.length,3);for(const mesh of warm.children){assert.equal(mesh.material.opacity,0);assert.equal(mesh.material.colorWrite,false);assert.equal(mesh.frustumCulled,false);}
  const page=stage.page({entry,page:1}),eve=page.actorTracks[1].actor,nativeMap=eve.getObjectByName('unfolded-map'),maps=[];stage.scene.traverse(n=>{if(n.userData.storyFilmProp==='map')maps.push(n);});assert.equal(nativeMap.visible,false);assert.equal(maps.length,2);const eveMap=maps.find(n=>n.parent===eve.userData.armL),heroMap=maps.find(n=>n.parent===stage.hero.userData.armL);assert.ok(eveMap&&heroMap);assert.equal(eveMap.position.z,.07);assert.equal(eveMap.rotation.x,.7);assert.equal(heroMap.position.z,.22);assert.equal(heroMap.rotation.x,-.4);assert.equal(eveMap.geometry,heroMap.geometry);assert.equal(eveMap.material,heroMap.material);remember();const initial=resources(stage.scene),held=stage.hero.userData.heroPieces.filter(n=>n.userData.baseKind==='longsword');assert.ok(held.length);
  stage.frame(11/1.16-.001);assert.equal(eveMap.visible,false);assert.equal(heroMap.visible,false);stage.frame(11/1.16);assert.equal(eveMap.visible,true);assert.equal(heroMap.visible,false);stage.frame(15/1.16);assert.equal(eveMap.visible,false);assert.equal(heroMap.visible,true);assert.ok(held.every(n=>!n.visible));for(let n=0;n<1800;n++)stage.frame(n/60);assert.deepEqual(resources(stage.scene),initial);assertPoses(before);
  stage.page({entry,page:2});remember();const fragment=stage.scene.getObjectByName('story-film-copper');assert.ok(fragment);assert.equal(fragment.parent,stage.hero.userData.armR);assert.equal(fragment.visible,true);assert.equal(nativeMap.visible,true);assert.equal(stage.scene.getObjectByName('story-film-map'),undefined);
  stage.page({text:'星奈望向雲海。'});assert.equal(stage.scene.getObjectByName('story-film-copper'),undefined);assert.ok(held.every(n=>n.visible));assert.equal(stage.scene.userData.storyActionPlan,null);assertPoses(before);stage.dispose();for(const [resource,count]of counts)assert.equal(count,1,resource.type+' owned film resource release');assertPoses(before);for(const resource of borrowed)resource.dispose();
});
test('the offered paper stays next to Eve’s palm and faces the film camera throughout its held narrative gesture without new resources',()=>{
  const env=heroEnvironment(),Actors=require('../story/tower-cinematic-actors.js'),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),original=env.TowerHeroVisuals.base('mage',env.buildCharacter,'hero','female'),before=poses(original),stage=Theater.create({THREE:T,hero:original,buildStoryActor:spec=>env.TowerCharacters.buildExplorer(spec.id,{THREE:T})}),page=stage.page({entry,page:1}),eve=page.actorTracks[1].actor,paper=eve.userData.armL.getObjectByName('story-film-map'),sessions=page.actorTracks.map(track=>Actors.create(track)),initial=resources(stage.scene);
  assert.ok(paper);assert.deepEqual(paper.position.toArray(),[0,-.34,.07]);assert.deepEqual(paper.rotation.toArray(),[.7,0,.1,'XYZ']);
  const cut=page.shot.cuts[2],normal=new T.Vector3(),position=new T.Vector3(),quaternion=new T.Quaternion(),cameraPosition=new T.Vector3(),towardCamera=new T.Vector3();
  for(const time of [12,13,14].map(t=>t/1.16)){
    stage.frame(time);for(const actor of sessions)actor.sample(time,{speaking:true,phase:'playing'});stage.scene.updateMatrixWorld(true);assert.equal(paper.visible,true);paper.getWorldQuaternion(quaternion);normal.set(0,0,1).applyQuaternion(quaternion);paper.getWorldPosition(position);const raw=Math.min(1,Math.max(0,(time-cut.at)/cut.duration)),progress=raw*raw*(3-2*raw);cameraPosition.copy(cut.goal).lerp(cut.goalTo,progress);towardCamera.copy(cameraPosition).sub(position).normalize();assert.ok(normal.z>.7,'held paper is upright rather than the old horizontal edge');assert.ok(normal.dot(towardCamera)>.55,'the camera can see a broad paper surface, not a white strip');assert.equal(paper.parent,eve.userData.armL);assert.deepEqual(resources(stage.scene),initial);assertPoses(before);
  }
  for(const actor of sessions)actor.restore();stage.dispose();assertPoses(before);for(const resource of resources(original))resource.dispose();
});
test('reduced motion still reveals narrative props while scripted actors and environment do not receive a second stage controller',()=>{
  const f=fixture({reduced:true}),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),page=f.stage.page({entry,page:1}),before=poses(f.stage.scene),heroBefore=poses(f.stage.hero),maps=[];f.stage.scene.traverse(n=>{if(n.userData.storyFilmProp==='map')maps.push(n);});
  const eveMap=maps.find(n=>n.parent===page.actorTracks[1].actor.userData.armL),heroMap=maps.find(n=>n.parent===f.stage.hero.userData.armL);page.frame(12/1.16);assert.equal(eveMap.visible,true);assert.equal(heroMap.visible,false);page.frame(17/1.16);assert.equal(eveMap.visible,false);assert.equal(heroMap.visible,true);for(const[n,p,q,s]of before){assert.deepEqual(n.position.toArray(),p);assert.deepEqual(n.quaternion.toArray(),q);assert.deepEqual(n.scale.toArray(),s);}assertPoses(heroBefore.filter(row=>!maps.includes(row[0])));f.stage.dispose();for(const resource of resources(f.actor))resource.dispose();
  const regular=fixture();regular.stage.page({entry,page:1});const posesBefore=poses(regular.stage.hero);regular.stage.frame(4);assertPoses(posesBefore);regular.stage.dispose();for(const resource of resources(regular.actor))resource.dispose();
});
test('full narrative acting keeps all profession faces and hand props above phone captions without scenery or prop occlusion',testContext=>{
  const env=heroEnvironment(),Actors=require('../story/tower-cinematic-actors.js'),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99),ray=new T.Raycaster(),point=new T.Vector3(),direction=new T.Vector3();let faceChecks=0,propChecks=0,minFaceMargin=Infinity,minPropMargin=Infinity;
  const visible=node=>{for(let p=node;p;p=p.parent)if(!p.visible)return false;return true;};
  for(const job of Object.keys(env.TowerHeroes.JOBS))for(const sex of ['male','female']){
    const original=env.TowerHeroVisuals.base(job,env.buildCharacter,'hero',sex),kind=env.TowerHeroes.JOBS[job].starter;env.TowerHeroVisuals.dress(T,original,{weapon:{...env.TowerHeroes.GEAR[kind],kind,durability:100}},()=>{});const before=poses(original),stage=Theater.create({THREE:T,hero:original,buildStoryActor:spec=>env.TowerCharacters.buildExplorer(spec.id,{THREE:T})});
    for(let page=0;page<3;page++){
      const spec=stage.page({entry,page}),sessions=spec.actorTracks.map(track=>Actors.create(track)),times=new Set([0,stage.scene.userData.storyActionPlan.duration]);for(const track of spec.actorTracks)for(const beat of track.beats)for(const time of [beat.at,beat.at+beat.duration/2,beat.at+beat.duration-.00001])times.add(time);for(const cut of spec.shot.cuts)for(const time of [cut.at,cut.at+.00001,Math.max(0,cut.at-.00001)])times.add(time);if(page===1)times.add(12.95);if(page===2)times.add(2);
      for(const time of [...times].sort((a,b)=>a-b)){
        stage.frame(time);for(const session of sessions)session.sample(time,{speaking:true,phase:'playing'});stage.scene.updateMatrixWorld(true);let cut=spec.shot.cuts[0];for(const next of spec.shot.cuts)if(next.at<=time)cut=next;const raw=Math.max(0,Math.min(1,(time-cut.at)/cut.duration)),progress=raw*raw*(3-2*raw),solid=[];stage.scene.getObjectByName('story-theater-environment').traverse(n=>{if(n.isMesh&&!n.material.transparent&&visible(n))solid.push(n);});stage.scene.traverse(n=>{if(n.isMesh&&!n.material.transparent&&visible(n)&&(n.parent?.userData.storyFilmProp==='copper'||n.userData.storyFilmProp==='map'))solid.push(n);});
        for(const [width,height,captionTop]of [[1440,900,643],[844,390,205],[568,320,135]]){
          const camera=new T.PerspectiveCamera(cut.fov,width/height,.1,100),focus=cut.focus.clone().lerp(cut.focusTo,progress);focus.y+=height<=340?-.24:height<=420?-.13:0;camera.position.copy(cut.goal).lerp(cut.goalTo,progress);camera.lookAt(focus);camera.updateMatrixWorld(true);
          for(const identity of cut.subjects){const actor=stage.scene.children.find(n=>n.userData.storyTheaterActor&&n.visible&&(n.userData.storyIdentity||'hero')===identity),head=actor.userData.headMesh||actor.userData.head;head.getWorldPosition(point);const world=point.clone(),p=point.clone().project(camera),x=(p.x+1)*width/2,y=(1-p.y)*height/2,label=[job,sex,page,cut.id,width,time.toFixed(3),identity].join(':');assert.ok(p.z>-1&&p.z<1,label+' depth');assert.ok(x>16&&x<width-16,label+' horizontal');assert.ok(y>16&&y<captionTop-16,label+' acting face-caption margin '+y);const top=point.clone();top.y+=.23;assert.ok(top.project(camera).y<.99,label+' animated head top');direction.copy(world).sub(camera.position);ray.set(camera.position,direction.normalize());ray.far=camera.position.distanceTo(world)-.12;assert.equal(ray.intersectObjects(solid,false).length,0,label+' face must not be covered by scenery or film props');minFaceMargin=Math.min(minFaceMargin,captionTop-y);faceChecks++;}
          if(page===1&&Math.abs(time-12.95)<.000001||page===2&&time===2){const kind=page===1?'map':'copper',prop=stage.hero.getObjectByName('story-film-'+kind);assert.ok(prop&&visible(prop));prop.getWorldPosition(point);const p=point.clone().project(camera),x=(p.x+1)*width/2,y=(1-p.y)*height/2,label=[job,sex,page,width,time,kind].join(':');assert.ok(p.z>-1&&p.z<1&&x>8&&x<width-8,label+' prop in screen');assert.ok(y>8&&y<captionTop-8,label+' prop above caption '+y);minPropMargin=Math.min(minPropMargin,captionTop-y);propChecks++;}
        }
      }
      for(const session of sessions)session.restore();
    }
    stage.dispose();assertPoses(before);for(const resource of resources(original))resource.dispose();
  }
  assert.ok(faceChecks>4000);assert.equal(propChecks,18*2*3);testContext.diagnostic(`${faceChecks} animated face checks, ${propChecks} prop checks; minimum face-caption margin ${minFaceMargin.toFixed(2)}px, prop-caption margin ${minPropMargin.toFixed(2)}px`);
});
test('the approved floor-99 arrival tracks keep their exact authored timing without generic idle motion',()=>{
  const f=fixture(),entry=require('../story/tower-narrative.js').SCENES.find(e=>e.floor===99);
  for(let page=0;page<3;page++){const spec=f.stage.page({entry,page});assert.ok(spec.actorTracks.length>=1);for(const track of spec.actorTracks)assert.equal(track.idleLife,false);}
  const later=f.stage.page({text:'你回望石台上的召喚陣。',page:1});for(const track of later.actorTracks||[])assert.notEqual(track.idleLife,false,'other pages stay lively');
  f.stage.dispose();for(const r of resources(f.actor))r.dispose();
});
