import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,statSync} from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),E=require('../story/tower-encounters.js'),L=require('../story/tower-lighting-core.js'),Intent=require('../story/tower-combat-intent.js'),Voices=require('../assets/character-voices.js'),T=require('../lib/three.min.js');
const fresh=(seed=43,job='mage',sex='male')=>H.enable(P.enable(C.newRun({seed,name:'測試旅人'}),job,sex).run).run;
function offered(type){for(let seed=1;seed<1000;seed++){const r=fresh(seed),q=E.explorerOffer(r);if(q?.type===type)return E.acceptQuest(r,q.id).run;}throw Error('no quest '+type);}
test('retired daylight migrates in-place, keeps actual XP, equipment, illumination and skill order',()=>{
  const old=fresh(),a=H.actor(old);a.skills=['arcane_bolt','thunder_wave','daylight'];a.cooldowns={arcane_bolt:0,thunder_wave:2,daylight:590};H.state(old).xpScale=10;H.state(old).xp=2600;old.party.light.daylight=590;old.party.light.cooldown=590;
  const before=JSON.stringify(old),loaded=C.validateSave(old);assert.ok(loaded);assert.equal(JSON.stringify(old),before);assert.deepEqual(H.actor(loaded).skills,['arcane_bolt','thunder_wave','thorn_growth']);assert.deepEqual(H.actor(loaded).cooldowns,{arcane_bolt:0,thunder_wave:2,thorn_growth:0});assert.equal(H.state(loaded).xp,2600);assert.equal(loaded.party.light.daylight,590);assert.deepEqual(loaded.equipment,old.equipment);assert.deepEqual(C.validateSave(loaded),loaded);
  const corrupt=structuredClone(old);H.state(corrupt).growth.choices='daylight';assert.equal(C.validateSave(corrupt),null);
});
test('all live mages have ten-minute innate daylight without spending a random skill or weapon durability',()=>{
  for(let seed=1;seed<=30;seed++){const r=fresh(seed),skills=[...H.actor(r).skills],dur=r.equipment.weapon.durability,out=L.daylight(r);assert.ok(out.ok);assert.equal(out.run.party.light.daylight,600);assert.deepEqual(H.actor(out.run).skills,skills);assert.equal(out.run.equipment.weapon.durability,dur);assert.ok(!skills.includes('daylight'));assert.equal(H.cast(r,'daylight').ok,false);assert.equal(L.daylight(out.run).ok,false);H.setHp(r,'hero',0);assert.equal(L.canCast(r),false);}
  assert.equal(L.canCast(fresh(43,'chef')),false);
});
test('thorn growth hits once, pays durability once, roots for three seconds and validates the saved status',()=>{
  let seed=1;while(!H.draft(seed,'mage','hero').skills.includes('thorn_growth'))seed++;
  let r=fresh(seed),m=P.monsterSpecs(r)[0],dur=r.equipment.weapon.durability,out=H.cast(r,'thorn_growth');assert.ok(out.ok);r=out.run;assert.equal(r.equipment.weapon.durability,dur-1);out=H.strike(r,m.id,{skillId:'thorn_growth'});assert.ok(out.ok);assert.equal(out.effect.dead,false);assert.equal(out.effect.rooted,true);r=out.run;assert.equal(H.state(r).enemy[m.id].root,3);assert.equal(r.equipment.weapon.durability,dur-1);assert.ok(C.validateSave(r));assert.equal(H.strike(r,m.id,{skillId:'thorn_growth'}).ok,false);H.tick(r,2.5);assert.equal(H.state(r).enemy[m.id].root,.5);H.tick(r,.5);assert.equal(H.state(r).enemy[m.id].root,0);
});
test('new quests never require the retired ordinary-attack stun; old quests accept verified root or defeat',()=>{
  let offers=0;for(let seed=1;seed<=500;seed++){const q=E.explorerOffer(fresh(seed));if(q){offers++;assert.notEqual(q.type,'stun');}}assert.ok(offers>60);
  let r=offered('defeat'),q=r.adventure.quest;q.type='stun';q.id=q.id.replace(':defeat:',':stun:');assert.ok(C.validateSave(r));assert.match(E.explorerOffer(r).description,/擊敗.*束縛/);assert.equal(E.questProgress(r,'root',{id:q.target}).ok,false);H.state(r).enemy[q.target]={root:3};let out=E.questProgress(r,'root',{id:q.target});assert.ok(out.ok);assert.equal(out.run.adventure.quest.status,'ready');out=E.claimQuestReward(out.run);assert.ok(out.ok);assert.equal(E.claimQuestReward(out.run).ok,false);
  r=offered('defeat');q=r.adventure.quest;q.type='stun';q.id=q.id.replace(':defeat:',':stun:');r.defeatedMonsters.push(q.target);assert.ok(E.questProgress(r,'defeat',{id:q.target}).ok);
});
test('escort needs the real exit and a nearby traveler; progress and reward are single-use',()=>{
  const r=offered('escort');for(const data of [{atExit:false,distance:1},{atExit:true,distance:3},{atExit:true,distance:NaN}])assert.equal(E.questProgress(r,'escort',data).ok,false);
  const done=E.questProgress(r,'escort',{atExit:true,distance:2.7});assert.ok(done.ok);assert.ok(C.validateSave(done.run));assert.equal(E.questProgress(done.run,'escort',{atExit:true,distance:1}).ok,false);const reward=E.claimQuestReward(done.run);assert.ok(reward.ok);assert.equal(E.claimQuestReward(reward.run).ok,false);
});
test('leader combat focus is bounded, cannot start through walls or from a follower, respects survive and expires',()=>{
  let blocked=false,policy='support';const m={alive:true,model:{position:{x:0,z:7}}},q=Intent.create({active:()=> 'hero',position:id=>({x:0,z:id==='hero'?0:-4}),clear:()=>!blocked,policy:()=>policy});assert.equal(q.engage(m,'ally'),false);blocked=true;assert.equal(q.engage(m,'hero'),false);blocked=false;assert.ok(q.engage(m,'hero'));assert.equal(q.target('ally'),m);policy='survive';assert.equal(q.target('ally'),null);policy='attack';q.tick(8);assert.equal(q.target('ally'),null);q.engage(m,'hero');m.alive=false;assert.equal(q.target('ally'),null);m.alive=true;m.model.position.z=13;assert.equal(q.engage(m,'hero'),false);
});
test('66 original recordings support all nine jobs with gender-matched robot reuse, dedicated cleric lines and no automatic narration matching',()=>{
  assert.equal(Object.keys(Voices.tracks).length,74);assert.equal(new Set(Object.values(Voices.tracks).map(v=>v.src)).size,66);const pack=require('../assets/voice-pack.js');for(const job of Object.keys(H.JOBS))for(const sex of ['male','female'])for(const event of Voices.events){const id='character.'+job+'.'+sex+'.'+event,v=Voices.tracks[id];assert.ok(v,id);assert.ok(statSync(new URL('../'+v.src,import.meta.url)).size>1500);if(job==='robot')assert.ok(v.src.includes('-'+sex+'-'));if(job==='cleric')assert.ok(v.src.includes('/cleric-'+sex+'-'),id+' has its own recording');assert.equal(pack.get(id).text,v.text);assert.equal(pack.exact(v.text,sex),null);assert.ok(pack.plan(v.text,sex).every(p=>!p.asset?.startsWith('character.')));}
  for(const sex of ['male','female']){const id='character.mage.'+sex+'.specialty.hope',v=Voices.tracks[id];assert.ok(statSync(new URL('../'+v.src,import.meta.url)).size>1500);assert.equal(pack.get(id).text,v.text);assert.equal(pack.exact(v.text,sex),null);assert.ok(pack.plan(v.text,sex).every(p=>!p.asset?.startsWith('character.')));}
});
function barks(){let run=fresh(),paused=false,speaking=false,enabled=true;const calls=[],env=vm.createContext({TowerHeroes:H});vm.runInContext(readFileSync(new URL('../assets/character-voices.js',import.meta.url),'utf8'),env);const voice={status:()=>({enabled,supported:true,speaking}),announceAsset(...args){calls.push(args);}};const api=env.MazeCharacterVoices.create({run:()=>run,voice,paused:()=>paused});return {api,calls,run:()=>run,pause:v=>paused=v,speaking:v=>speaking=v,enable:v=>enabled=v};}
test('short lines use team 12-second and actor-event 45-second cooldown, never queue or interrupt reading',()=>{
  const f=barks();assert.ok(f.api.say('battle','hero'));assert.equal(f.api.say('victory','hero'),false);f.api.tick(12);assert.ok(f.api.say('victory','hero'));f.api.tick(12);assert.equal(f.api.say('battle','hero'),false);f.api.tick(21);f.speaking(true);assert.equal(f.api.say('battle','hero'),false);f.speaking(false);assert.ok(f.api.say('battle','hero'));f.api.tick(12);f.pause(true);assert.equal(f.api.say('specialty','hero'),false);assert.ok(f.api.say('specialty','hero',{allowPaused:true}));assert.equal(f.calls.at(-1)[3].gender,'male');f.api.reset();f.enable(false);assert.equal(f.api.say('battle','hero'),false);
});
test('low-health lines rearm only after recovery above half health, not at every hit',()=>{
  const f=barks(),r=f.run();H.setHp(r,'hero',H.maxHp(r)*.2);f.api.tick(.01);assert.equal(f.calls.length,1);f.api.tick(50);assert.equal(f.calls.length,1);H.setHp(r,'hero',H.maxHp(r)*.4);f.api.tick(50);assert.equal(f.calls.length,1);H.setHp(r,'hero',H.maxHp(r)*.6);f.api.tick(.01);H.setHp(r,'hero',H.maxHp(r)*.2);f.api.tick(.01);assert.equal(f.calls.length,2);
});
test('volume persistence, independent zero gain and narration ducking keep the chosen percentages',()=>{
  const saved=new Map(),env=vm.createContext({localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)}});vm.runInContext(readFileSync(new URL('../assets/audio-settings.js',import.meta.url),'utf8'),env);const mix=env.MazeAudioSettings,levels={},engine={ctx:{currentTime:0}};for(const k of ['musicGain','fxGain','itemGain'])engine[k]={gain:{setTargetAtTime:v=>levels[k]=v}};mix.connect(engine);assert.ok(mix.set('music',50));assert.ok(mix.set('effects',25));assert.deepEqual(levels,{musicGain:.16,fxGain:.2,itemGain:.1});mix.duck(true);assert.deepEqual(levels,{musicGain:.045,fxGain:.1125,itemGain:.04});mix.set('effects',0);mix.duck(false);assert.deepEqual(levels,{musicGain:.16,fxGain:0,itemGain:0});assert.equal(mix.set('unknown',0),false);assert.equal(mix.set('music',NaN),false);assert.equal(mix.set('effects',101),false);assert.match(mix.controls(),/type="range"/);assert.deepEqual(JSON.parse(saved.get('maze3d_audio_mix_v1')),{music:50,effects:0});
});
test('lightning and thorn effects use distinct original solid geometry, textures, lifetimes and finite mesh budgets',()=>{
  const env=vm.createContext({});vm.runInContext(readFileSync(new URL('../story/tower-skill-effects.js',import.meta.url),'utf8'),env);const world=new T.Group(),fx=env.TowerSkillEffects.create(T,{world:()=>world}),shock=fx.emit(H.SKILLS.thunder_wave,{x:0,z:0}),thorn=fx.emit(H.SKILLS.thorn_growth,{x:2,z:0},0,{impact:true});assert.equal(shock.family,'storm');assert.equal(thorn.family,'thorns');assert.equal(thorn.total,3);assert.notEqual(shock.mats[0].color.getHex(),thorn.mats[0].color.getHex());assert.ok(shock.group.children.some(o=>o.geometry?.type==='ShapeGeometry'));assert.ok(thorn.group.children.some(o=>o.geometry?.type==='TubeGeometry'));for(let i=0;i<20;i++)fx.emit(H.SKILLS.thunder_wave,{x:0,z:0});assert.equal(fx.stats().groups,12);assert.ok(fx.stats().meshes<=96);world.traverse(o=>assert.ok(!o.isLine&&!o.isLight));fx.tick(4);assert.equal(world.children.length,0);const sound=require('../assets/combat-audio.js');assert.notDeepEqual(sound.render('thunder'),sound.render('thorns'));assert.equal(sound.skillKind(H.SKILLS.thunder_wave),'thunder');
});
