import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {provisionTravellers} from './recruit-fixtures.mjs';
const require=createRequire(import.meta.url),C=require('../story/story-core.js'),P=require('../story/tower-party-core.js'),H=require('../story/tower-heroes-core.js'),G=require('../story/tower-hero-growth.js'),R=H.ROBOT,N=require('../story/tower-narrative.js'),D=require('../story/tower-dungeons.js'),U=require('../story/tower-underworld.js');
const fresh=(seed=123,job='robot')=>provisionTravellers(H.enable(P.enable(C.newRun({seed,name:'機甲測試'}),job).run).run);
function floor(run,f){run.floor=f;run.floorsCleared=f>0?99-f:99;run.chronicle=N.newChronicle(f);run.expedition=D.newExpedition();run.claimed=[];run.defeatedMonsters=[];run.monsterStuns={};P.advance(run,{reward:false});return run;}
function owns(run,key){const a=H.actor(run),def=H.SKILLS[key]||H.PASSIVES[key],list=def.attack!==undefined?a.skills:a.passives;if(!list.includes(key)){if(def.unique){G.record(run).awakening=key;list.push(key);if(def.attack!==undefined)a.cooldowns[key]=0;}else{const pool=Object.values(def.attack!==undefined?H.SKILLS:H.PASSIVES).filter(s=>s.job==='robot'&&!s.unique&&s.id!==key);if(def.attack!==undefined){const other=pool.find(s=>s.attack!==def.attack);a.skills=[key,other.id,pool.find(s=>s.id!==other.id).id];a.cooldowns=Object.fromEntries(a.skills.map(s=>[s,0]));}else a.passives=[key,pool[0].id];}}return run;}
function underground(run){floor(run,1);run.chronicle.ending='keeper';run.chronicle.clues.push(N.chapterForFloor(1).clueId);run.party.boss.started=true;run.party.boss.done=true;run.party.boss.seals.fill(true);run.defeatedMonsters.push(require('../story/tower-floor-lords.js').spec(run).id);const end=C.descend(run);assert.ok(end.ok,end.message);const next=C.startUnderworld(end.run);assert.ok(next.ok,next.message);return next.run;}
test('robot has six active/five passive skills, first-rank body +5 then +5 per rank, stable legal drafts',()=>{
  assert.deepEqual(H.PASSIVES.robot_body.power,[5,10,15,20,25,30]);assert.equal(Object.values(H.SKILLS).filter(s=>s.job==='robot'&&!s.unique).length,6);assert.equal(Object.values(H.PASSIVES).filter(s=>s.job==='robot'&&!s.unique).length,5);
  for(let seed=1;seed<=250;seed++){const r=fresh(seed),a=H.actor(r);assert.equal(a.skills.length,3);assert.equal(a.passives.length,2);assert.ok(a.skills.some(k=>H.SKILLS[k].attack));assert.ok(a.skills.some(k=>!H.SKILLS[k].attack));assert.deepEqual(C.validateSave(JSON.stringify(r)),r);assert.equal(H.maxHp(r),P.vitalHp('robot',1,true)+(a.passives.includes('robot_body')?5:0));}
  const r=owns(fresh(),'robot_body');for(let l=1;l<=10;l++){H.state(r).level=l;assert.equal(H.maxHp(r),P.vitalHp('robot',l,true)+5*(l>=10?6:Math.min(5,l)));}
});
test('five fixed part tiers are gated, normal pools exclude parts, ordinary gear cannot replace or detach them',()=>{
  assert.equal(Object.keys(R.GEAR).filter(R.isPart).length,10);assert.equal(Object.keys(R.CORES).length,5);for(const base of ['robot_fists','robot_shell'])for(let tier=1;tier<=5;tier++){const d=R.GEAR[R.kind(base,tier)],g=C.createGear(d.kind,99,123,'fixed');assert.equal(g.maxDurability,d.maxDurability);assert.deepEqual(C.validateGear(g),g);assert.equal(d.requiredLevel,[1,3,5,8,10][tier-1]);for(const key of ['defense','maxDurability','bonus']){const bad={...g,[key]:g[key]+1};assert.equal(C.validateGear(bad),null);}}
  const r=fresh();assert.ok(!H.gearPool(-50).some(R.isPart));assert.equal(r.equipment.helmet,null);assert.equal(r.equipment.shield,null);assert.equal(H.canEquip(r,'hero',C.createGear('heavy_armor',99,r.seed,'wrong')),false);assert.equal(H.unequip(r,'hero','weapon').ok,false);assert.equal(H.equip(r,'hero',r.equipment.weapon.id).ok,false);
  r.equipment.weapon.durability=0;r.equipment.armor.durability=0;r.equipment.core1.durability=0;assert.equal(H.stats(r).damage,3);assert.equal(H.stats(r).armor,4);assert.ok(C.validateSave(r));
});
test('ordinary punching misses are free, every four real basic hits wear once, skills wear once per cast',()=>{
  let r=floor(owns(fresh(),'shoulder_quake'),1),w=r.equipment.weapon.durability;assert.equal(H.strike(r,'not-a-monster').ok,false);assert.equal(r.equipment.weapon.durability,w);
  for(let i=0;i<4;i++){H.actor(r).attack=0;r.party.health['monster-0']=200;const q=H.strike(r,'monster-0');assert.ok(q.ok);r=q.run;assert.equal(r.equipment.weapon.durability,w-(i===3?1:0));assert.ok(C.validateSave(r));}
  H.actor(r).attack=0;r=H.cast(r,'shoulder_quake').run;w=r.equipment.weapon.durability;for(const m of P.monsterSpecs(r).slice(0,3)){const q=H.strike(r,m.id,{skillId:'shoulder_quake'});assert.ok(q.ok);r=q.run;}assert.equal(r.equipment.weapon.durability,w-1);assert.equal(H.strike(r,P.monsterSpecs(r)[3].id,{skillId:'shoulder_quake'}).ok,false);assert.ok(C.validateSave(r));
});
test('guard and lubrication are self-only, bounded; part restore consumes one scrap not HP/gear/ingredients',()=>{
  for(const key of ['folded_guard','joint_oil','parts_restore']){let r=owns(fresh(),key);H.setHp(r,'hero',20);const ingredients=structuredClone(r.party.ingredients),wear=r.equipment.armor.durability;const q=H.cast(r,key);assert.ok(q.ok,key);r=q.run;assert.deepEqual(r.party.ingredients,ingredients);assert.equal(r.equipment.armor.durability,wear);if(key==='parts_restore'){assert.equal(r.party.journey.scrap,29);assert.equal(r.hp,38);}else{const b=H.buff(r,key==='folded_guard'?'robot_guard':'robot_speed');assert.equal(b.left,key==='folded_guard'?6:8);assert.equal(H.speed(r),key==='folded_guard'?.45:.9*1.12);}assert.ok(C.validateSave(r));}
  const r=owns(fresh(),'parts_restore');r.party.journey.scrap=0;H.setHp(r,'hero',20);const before=JSON.stringify(r);assert.equal(H.cast(r,'parts_restore').ok,false);assert.equal(JSON.stringify(r),before);H.state(r).growth.policies.hero.materials=false;assert.notEqual(G.aiChoice(r,'hero',['hero'],true)?.skill,'parts_restore');
});
test('calibration is charged by actual stillness, used once on a basic hit and never reset through save/shift',()=>{
  let r=floor(owns(fresh(),'power_calibration'),1);for(let i=0;i<4;i++)H.noteMovement(r,'hero',false,.25);assert.equal(H.actor(r).robot.calibrationReady,true);const normal=H.stats(r).damage;let q=H.strike(r,'monster-0');assert.ok(q.ok);r=q.run;assert.equal(q.effect.damage,Math.round(normal*1.1));assert.equal(H.actor(r).robot.calibrationLeft,6);assert.equal(H.actor(r).robot.calibrationReady,false);r=C.validateSave(JSON.stringify(r));assert.equal(H.actor(r).robot.calibrationLeft,6);H.advance(r,{reward:false});assert.equal(H.actor(r).robot.calibrationLeft,6);H.tick(r,6);H.noteMovement(r,'hero',true,.25);assert.equal(H.actor(r).robot.stationary,0);
});
test('kinetic awakening charges only actual monster injury; a basic attack grants five-minute shield; cooldown persists',()=>{
  let r=floor(fresh(),1);H.gainXp(r,G.XP[9]);const a=H.actor(r),g=G.record(r);if(g.awakening!== 'kinetic_core'){a.skills=a.skills.filter(k=>k!=='steel_meteor_fist');delete a.cooldowns.steel_meteor_fist;a.passives=a.passives.filter(k=>k!=='kinetic_core');a.passives.push('kinetic_core');g.awakening='kinetic_core';}assert.ok(C.validateSave(r));
  H.hurt(r,'hero',10,'trap');assert.equal(a.robot.energyLeft,0);a.hurt=0;H.hurt(r,'hero',10,'hunger');assert.equal(a.robot.energyLeft,0);a.hurt=0;G.shield(r,'hero',100);H.hurt(r,'hero',10,'monster');assert.equal(a.robot.energyLeft,0);a.buffs=[];a.hurt=0;H.hurt(r,'hero',10,'monster');assert.equal(a.robot.energyLeft,8);assert.equal(a.robot.energyCooldown,30);const q=H.strike(r,'monster-0');assert.ok(q.ok);r=q.run;assert.equal(q.effect.kinetic,true);assert.equal(H.buff(r,'barrier').left,300);assert.equal(H.actor(r).robot.energyLeft,0);assert.equal(H.actor(r).robot.energyCooldown,30);assert.ok(C.validateSave(r));H.advance(r,{reward:false});assert.equal(H.actor(r).robot.energyCooldown,30);
});
test('robot tier upgrade is finite, atomic, material-backed, preserves wear percentage and tier gates',()=>{
  let r=fresh(4,'smith');floor(r,85);const offer=P.recruitOffer(r);assert.equal(offer.profession,'robot');r=P.recruit(r,offer.id).run;const id=offer.id;H.state(r).level=5;H.gainXp(r,G.XP[4]);r.party.members.find(m=>m.id===id).level=5;const e=H.equipment(r,id);e.armor.durability=60;const before=JSON.stringify(r);assert.equal(H.upgradeRobot(r,id,'armor',{safe:false}).ok,false);assert.equal(JSON.stringify(r),before);const q=H.robotUpgradeQuote(r,id,'armor',{safe:true});assert.equal(q.to,2);assert.equal(q.allowed,true);r.coins=9999;r=H.upgradeRobot(r,id,'armor',{safe:true}).run;assert.equal(H.equipment(r,id).armor.kind,'robot_shell_t2');assert.equal(H.equipment(r,id).armor.durability,80);r=H.upgradeRobot(r,id,'armor',{safe:true}).run;assert.equal(H.equipment(r,id).armor.kind,'robot_shell_t3');assert.equal(H.upgradeRobot(r,id,'armor',{safe:true}).ok,false);assert.ok(C.validateSave(r));
});
test('dismissed robot keeps unique integrated parts and wear, rejoining never issues new kit',()=>{
  let r=floor(fresh(4,'smith'),85),offer=P.recruitOffer(r);r=P.recruit(r,offer.id).run;const id=offer.id,e=H.equipment(r,id);e.armor.durability=23;e.weapon.durability=9;const saved=structuredClone(e),count=r.gearBag.length;r=P.dismiss(r,id).run;assert.equal(r.gearBag.length,count);assert.deepEqual(r.party.travellers[0].loadout.robotEquipment,saved);assert.ok(C.validateSave(r));for(let f=84;f>=1;f--){floor(r,f);offer=P.recruitOffer(r);if(offer?.id===id)break;}assert.equal(offer.id,id);r=P.recruit(r,id).run;assert.deepEqual(H.equipment(r,id),saved);assert.ok(C.validateSave(r));
});
test('save validator rejects malicious robot counters, normal gear and hidden integrated parts in bag',()=>{
  const r=fresh();for(const [key,v]of [['fistHits',4],['stationary',2],['energyLeft',9],['energyCooldown',31],['calibrationReady',1]]){const bad=structuredClone(r);H.actor(bad).robot[key]=v;assert.equal(C.validateSave(bad),null,key);}const bad=structuredClone(r);bad.gearBag.push(C.createGear('robot_shell',99,r.seed,'hidden'));assert.equal(C.validateSave(bad),null);const gear=structuredClone(r);gear.equipment.armor=C.createGear('heavy_armor',99,r.seed,'invalid');assert.equal(C.validateSave(gear),null);
});
test('underground-only levels, chosen branches and tier-four/five upgrades retain a valid bounded save',()=>{
  for(const ultimate of ['steel_meteor_fist','kinetic_core']){let r=underground(fresh(4));H.gainXp(r,G.XP[9]);assert.equal(G.availableUltimate(r),true);r=G.chooseUltimate(r,'hero',ultimate).run;assert.equal(G.chooseUltimate(r,'hero',ultimate).ok,false);const skills=H.actor(r).skills.length,passives=H.actor(r).passives.length;H.gainXp(r,G.XP[11]-H.state(r).xp);assert.equal(H.level(r),12);assert.equal(H.actor(r).skills.length,skills+1);H.gainXp(r,G.XP[14]-H.state(r).xp);assert.equal(H.level(r),15);assert.equal(H.actor(r).passives.length,passives+1);assert.ok(C.validateSave(r));
    const extension=ultimate==='steel_meteor_fist'?'explosive_fists':'mech_aid',q=H.cast(r,extension);assert.ok(q.ok,q.message);if(extension==='mech_aid'){assert.equal(H.buff(q.run,'barrier').left,300);assert.equal(H.buff(q.run,'barrier').power,H.maxHp(q.run)*.35*1.3);}assert.ok(C.validateSave(q.run));
  }
  let r=underground(fresh(4));r.coins=9999;r.party.journey.scrap=99;const smith={id:'part-upgrade-smith',profession:'smith',sex:'male',level:5,hp:58,cooldown:0,hurtLeft:0};r.party.members.push(smith);r.party.joined.push(smith.id);H.addMember(r,smith);H.gainXp(r,G.XP[7]);
  for(const slot of ['armor','weapon']){const original=H.equipment(r,'hero')[slot],id=original.id;original.durability=original.maxDurability/2;for(const tier of [2,3,4]){const q=H.robotUpgradeQuote(r,'hero',slot,{safe:true}),before=structuredClone(r);assert.equal(q.to,tier);const out=H.upgradeRobot(r,'hero',slot,{safe:true});assert.ok(out.ok,out.message);r=out.run;const g=H.equipment(r,'hero')[slot];assert.equal(g.id,id);assert.equal(g.durability/g.maxDurability,.5);assert.equal(r.coins,before.coins-q.costs.coins);assert.equal(r.party.journey.scrap,before.party.journey.scrap-q.costs.scrap);assert.equal(r.gearBag.length,before.gearBag.length);assert.ok(C.validateSave(r));}assert.equal(H.upgradeRobot(r,'hero',slot,{safe:true}).ok,false,'fifth tier needs level ten');}
  H.gainXp(r,G.XP[9]-H.experience(r));for(const slot of ['armor','weapon']){const out=H.upgradeRobot(r,'hero',slot,{safe:true});assert.ok(out.ok,out.message);r=out.run;assert.equal(R.GEAR[H.equipment(r,'hero')[slot].kind].tier,5);assert.equal(H.equipment(r,'hero')[slot].durability/H.equipment(r,'hero')[slot].maxDurability,.5);const before=JSON.stringify(r);assert.equal(H.upgradeRobot(r,'hero',slot,{safe:true}).ok,false);assert.equal(JSON.stringify(r),before);}assert.ok(C.validateSave(r));
});
test('merchant upgrade is iron-smith only and full quote/revision/resource checks are atomic',()=>{
  const E=require('../story/tower-encounters.js');let r;for(let seed=1;seed<=50;seed++){const n=fresh(seed);if(E.serviceContext(n,'tieLing')){r=n;break;}}assert.ok(r);H.gainXp(r,G.XP[2]);r.coins=9999;const service=E.serviceContext(r,'tieLing'),q=H.robotUpgradeQuote(r,'hero','armor',{service});assert.equal(q.allowed,true);assert.equal(q.costs.coins,Math.ceil(R.COSTS[2].coins*1.2));assert.equal(H.upgradeRobot(r,'hero','armor',{safe:true}).ok,false);assert.equal(H.upgradeRobot(r,'hero','armor',{service},r.revision+1).ok,false);const before=JSON.stringify(r);const poor=structuredClone(r);poor.party.journey.materials.ironore=0;assert.equal(H.upgradeRobot(poor,'hero','armor',{service}).ok,false);assert.equal(JSON.stringify(r),before);const out=H.upgradeRobot(r,'hero','armor',{service});assert.ok(out.ok,out.message);assert.ok(C.validateSave(out.run));assert.equal(out.run.coins,r.coins-q.costs.coins);const wrong={...service,merchantId:'jinHe'};assert.equal(H.robotUpgradeQuote(r,'hero','armor',{service:wrong}).allowed,false);
});
test('forced underground farewell keeps robot parts with original wearer and does not overflow bag',()=>{
  let r=floor(fresh(4,'smith'),85),offer=P.recruitOffer(r);r=P.recruit(r,offer.id).run;const id=offer.id,parts=H.equipment(r,id);parts.armor.durability=17;parts.weapon.durability=8;const saved=structuredClone(parts),count=r.gearBag.length;r=underground(r);assert.equal(r.party.members.length,0);assert.equal(r.gearBag.length,count);assert.equal(r.underworld.departed.profession,'robot');assert.deepEqual(r.party.travellers[0].loadout.robotEquipment,saved);assert.ok(C.validateSave(r));
});
